/**
 * Admin component import map (D60).
 *
 * Generates a TypeScript module that statically imports every plugin admin
 * component referenced by `contributes.admin` (pages, settings, per-collection
 * views) and registers them via `registerComponents`. Importing this generated
 * module from the admin shell makes plugin React components load with **no
 * manual host imports** and **no run-once dynamic-import race** (the P5 gap) —
 * completing the string-path component registry (D19).
 *
 * Menu items carry only a route (`to`), not a component, so they contribute no
 * paths. Widgets (D22) are RESERVED / not rendered in P5, so they are excluded
 * (generating an import for an unrendered/maybe-absent component would break the
 * module).
 *
 * Pure — no IO. The CLI writes the returned string to a generated file.
 *
 * @module plugins/codegen/component-import-map
 */

import { dirname, join } from "node:path";

import type { PluginDefinition } from "../plugin-context";

/** Filename of the generated admin component import map (D60). */
export const COMPONENT_IMPORT_MAP_FILENAME =
  "plugin-admin-imports.generated.ts";

const HEADER = [
  "/* AUTO-GENERATED by `nextly generate:types` — DO NOT EDIT.",
  " * Statically registers the plugin admin components referenced by",
  " * `contributes.admin` so they load without manual host imports (D60). */",
].join("\n");

/**
 * Collect every admin `ComponentPath` an ENABLED plugin contributes (pages,
 * settings, per-collection views). Disabled plugins contribute no behavior (D49).
 */
export function collectAdminComponentPaths(plugin: PluginDefinition): string[] {
  if (plugin.enabled === false) return [];
  const admin = plugin.contributes?.admin;
  if (!admin) return [];

  const paths: string[] = [];
  for (const page of admin.pages ?? []) paths.push(page.component);
  if (admin.settings) paths.push(admin.settings.component);
  for (const view of Object.values(admin.views ?? {})) {
    for (const slot of [
      view.list,
      view.edit,
      view.beforeList,
      view.afterList,
      view.beforeEdit,
      view.afterEdit,
    ]) {
      if (slot) paths.push(slot);
    }
  }
  return paths;
}

interface ParsedPath {
  /** The full component path string (the registry key). */
  path: string;
  /** Module specifier (before `#`). */
  module: string;
  /** Named export (after `#`), or `"default"` when there is no `#`. */
  member: string;
}

function parsePath(path: string): ParsedPath {
  const hash = path.indexOf("#");
  if (hash === -1) return { path, module: path, member: "default" };
  return { path, module: path.slice(0, hash), member: path.slice(hash + 1) };
}

/**
 * Build the generated import-map module source for all plugins' admin
 * components. Deterministic: modules and registry keys are sorted; one
 * `import * as` per unique module; duplicate paths deduped. Returns a valid
 * (no-op) module when there are no admin components.
 */
export function buildComponentImportMap(plugins: PluginDefinition[]): string {
  const byPath = new Map<string, ParsedPath>();
  for (const plugin of plugins) {
    for (const path of collectAdminComponentPaths(plugin)) {
      if (!byPath.has(path)) byPath.set(path, parsePath(path));
    }
  }

  if (byPath.size === 0) {
    return `${HEADER}\n\nexport {};\n`;
  }

  const parsed = Array.from(byPath.values());
  const modules = Array.from(new Set(parsed.map(p => p.module))).sort();
  const alias = new Map<string, string>();
  modules.forEach((m, i) => alias.set(m, `_p${i}`));

  const lines: string[] = [HEADER, ""];
  lines.push('import { registerComponents } from "@nextlyhq/admin";');
  for (const m of modules) {
    lines.push(`import * as ${alias.get(m)} from "${m}";`);
  }
  lines.push("");
  lines.push("registerComponents({");
  for (const p of parsed.sort((a, b) => a.path.localeCompare(b.path))) {
    lines.push(
      `  ${JSON.stringify(p.path)}: ${alias.get(p.module)}.${p.member},`
    );
  }
  lines.push("});");
  lines.push("");
  return lines.join("\n");
}

/**
 * Decide whether to emit a component import map and where. Returns `null` when
 * no enabled plugin contributes admin components (nothing to register) — the
 * caller then writes no file. The map is placed alongside the generated types
 * file so it ships with the app; importing it self-registers the components
 * (it calls `registerComponents` from `@nextlyhq/admin`). Pure — no IO.
 */
export function buildImportMapArtifact(
  plugins: PluginDefinition[],
  typesOutputPath: string
): { path: string; code: string } | null {
  const hasAdminComponents = plugins.some(
    p => collectAdminComponentPaths(p).length > 0
  );
  if (!hasAdminComponents) return null;

  return {
    path: join(dirname(typesOutputPath), COMPONENT_IMPORT_MAP_FILENAME),
    code: buildComponentImportMap(plugins),
  };
}
