/**
 * Admin component import map.
 *
 * Generates a TypeScript module that statically imports every plugin admin
 * component the admin can resolve by string — pages, settings and
 * per-collection views from `contributes.admin`, the header/schema-builder/
 * form-toolbar slots, and field-type editor components from
 * `contributes.fieldTypes` — and registers them via `registerComponents`.
 * Importing this generated module from the admin shell makes plugin React
 * components load with **no manual host imports** and **no run-once
 * dynamic-import race** (the P5 gap) — completing the string-path component
 * registry.
 *
 * Menu items carry only a route (`to`), not a component, so they contribute no
 * paths. Widgets are RESERVED / not rendered, so they are excluded
 * (generating an import for an unrendered/maybe-absent component would break
 * the module).
 *
 * Pure — no IO. The CLI writes the returned string to a generated file.
 *
 * @module plugins/codegen/component-import-map
 */

import { dirname, join } from "node:path";

import type {
  ComponentPath,
  PluginAdminContributions,
} from "../admin-contributions";
import { collectDeclarations } from "../declarations";
import type { PluginDefinition } from "../plugin-context";

import { isPageBuilderActive, PAGE_BUILDER_PLUGIN } from "./block-manifest";

/** Filename of the generated admin component import map. */
export const COMPONENT_IMPORT_MAP_FILENAME =
  "plugin-admin-imports.generated.ts";

const HEADER = [
  "/* AUTO-GENERATED by `nextly generate:types` — DO NOT EDIT.",
  " * Statically registers the plugin admin components the admin resolves by",
  " * string (pages, settings, views, slots, field-type editors) so they load",
  " * without manual host imports. */",
].join("\n");

/**
 * Header, schema-builder and form-toolbar slots. They render through the
 * same registry from surfaces the plugin does not own, so they need the
 * map's import as much as a page does.
 */
function collectAdminSlotPaths(admin: PluginAdminContributions): string[] {
  // `header.slot` supersedes the deprecated top-level spelling; both are
  // read exactly as admin-meta reads them.
  const headerSlot = admin.header?.slot ?? admin.headerSlot;
  return [
    headerSlot,
    admin.schemaBuilderSlot,
    admin.entryFormToolbarSlot,
  ].filter((path): path is ComponentPath => Boolean(path));
}

/**
 * Collect every admin `ComponentPath` a plugin contributes that the admin
 * can resolve by string: pages, settings, per-collection views, header and
 * schema-builder and form-toolbar slots, and field-type editor components.
 * Behavioral UI (everything but field types) exists only for an ENABLED
 * plugin; field-type editors are collected regardless, because a disabled
 * plugin keeps its collections and their fields — admin-meta serializes
 * their types for exactly that reason, and a retained field renders empty
 * without its editor module.
 *
 * The set must stay a superset of what `buildPluginAdminMeta` exposes: the
 * browser resolves each of those strings through the component registry, and
 * the generated map is the only guaranteed importer of the modules behind
 * them — the registry's runtime fallback cannot resolve a bare package
 * specifier in a bundled browser. The parity test beside this module fails
 * when admin-meta grows a path kind this collector has not learned.
 */
export function collectAdminComponentPaths(plugin: PluginDefinition): string[] {
  // Field-type editor components live under `contributes` rather than
  // `contributes.admin` because that is where a type is declared, but they
  // are admin components in every other sense: the entry form resolves the
  // string through the same registry a page or settings view uses. A plugin
  // contributing only field types — the page builder, whose one component is
  // its blocks control — contributes no pages, settings or views, so without
  // this the generated map imports nothing of it and the field can only
  // render through a fallback that cannot fire.
  //
  // Collected for a DISABLED plugin too, where the block-editor collector
  // below drops everything once the page builder is disabled. The two rules
  // read as opposed and are not: a retained collection still renders its
  // fields, so their editors still mount and still need their modules, while
  // a block editor has no registry to land in once the page builder stops
  // booting, so importing one would pull in a bundle for a feature that
  // cannot run. Field types follow what still RENDERS; block editors follow
  // what still RUNS.
  const fieldTypePaths = (plugin.contributes?.fieldTypes ?? []).map(
    fieldType => fieldType.component
  );

  const admin = plugin.contributes?.admin;
  if (plugin.enabled === false || !admin) return fieldTypePaths;

  const paths = [...fieldTypePaths];
  for (const page of admin.pages ?? []) paths.push(page.component);
  if (admin.settings) paths.push(admin.settings.component);
  paths.push(...collectCollectionViewPaths(admin.views));
  paths.push(...collectWidgetPaths(admin.widgets));
  paths.push(...collectAdminSlotPaths(admin));
  return paths;
}

/**
 * Every override and injection point a plugin declares per collection.
 *
 * Its own function rather than two nested loops inline, because the six slots
 * are one list and the enclosing collector already answers several unrelated
 * questions -- pages, settings, field types, header slots, widgets. Flattening
 * them all into one body is what pushed it past the complexity gate.
 */
function collectCollectionViewPaths(
  views: PluginAdminContributions["views"]
): string[] {
  const paths: string[] = [];
  for (const view of Object.values(views ?? {})) {
    for (const slot of [
      view.list,
      view.edit,
      view.beforeList,
      view.afterList,
      view.beforeEdit,
      view.afterEdit,
    ]) {
      if (slot) paths.push(slot);
    }
  }
  return paths;
}

/**
 * Every widget component a plugin declares.
 *
 * Being pre-bundled by this map is what puts a component in the registry
 * `PluginSlot` reads; the registry's runtime fallback cannot resolve a bare
 * package specifier in a bundled browser. So while widgets were excluded here,
 * a `custom` widget drew its card and then nothing inside it, unless the plugin
 * called `registerComponents` itself from its admin entry -- which the
 * documented contract never asked it to do.
 */
function collectWidgetPaths(
  widgets: PluginAdminContributions["widgets"]
): string[] {
  // Optional now: a declarative widget names an archetype and a query and ships
  // no component at all, so only the ones that HAVE a path contribute one.
  return (widgets ?? []).flatMap(widget =>
    widget.component ? [widget.component] : []
  );
}

/**
 * Every editor component a declared block names.
 *
 * A block may supply its own inspector or canvas component through
 * `editor.component`, which is a `ComponentPath` like any admin contribution —
 * so the editor bundle can load it the same way, with no hand-written import.
 *
 * Read from declarations rather than from the block registry, for the reason
 * declarations exist: the registry is populated by `init`, and generation runs
 * no plugin. A block registered imperatively contributes no path here, exactly
 * as it contributes no manifest entry.
 *
 * Malformed declarations are skipped rather than refused. The manifest emitter
 * already validates them and fails generation loudly; repeating the check here
 * would report the same defect twice, and an import map is not the place a
 * schema error should surface.
 */
export function collectBlockEditorComponentPaths(
  plugins: readonly PluginDefinition[]
): string[] {
  const paths: string[] = [];
  // No page builder, no registry for these blocks to land in, so their editor
  // components would be imported eagerly for a feature that cannot run. The
  // manifest applies the same rule; disagreeing would describe two different
  // apps from one config.
  if (!isPageBuilderActive(plugins)) return paths;
  for (const declaration of collectDeclarations(plugins, PAGE_BUILDER_PLUGIN)) {
    const value = declaration.value;
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      continue;
    }
    const blocks = (value as { blocks?: unknown }).blocks;
    if (!Array.isArray(blocks)) continue;
    for (const block of blocks) {
      if (typeof block !== "object" || block === null) continue;
      const editor = (block as { editor?: unknown }).editor;
      if (typeof editor !== "object" || editor === null) continue;
      const component = (editor as { component?: unknown }).component;
      if (typeof component === "string" && component.length > 0) {
        paths.push(component);
      }
    }
  }
  return paths;
}

interface ParsedPath {
  /** The full component path string (the registry key). */
  path: string;
  /** Module specifier (before `#`). */
  module: string;
  /** Named export (after `#`), or `"default"` when there is no `#`. */
  member: string;
}

function parsePath(path: string): ParsedPath {
  const hash = path.indexOf("#");
  if (hash === -1) return { path, module: path, member: "default" };
  return { path, module: path.slice(0, hash), member: path.slice(hash + 1) };
}

/**
 * Build the generated import-map module source for all plugins' admin
 * components. Deterministic: modules and registry keys are sorted; one
 * `import * as` per unique module; duplicate paths deduped. Returns a valid
 * (no-op) module when there are no admin components.
 */
export function buildComponentImportMap(plugins: PluginDefinition[]): string {
  const byPath = new Map<string, ParsedPath>();
  for (const plugin of plugins) {
    for (const path of collectAdminComponentPaths(plugin)) {
      if (!byPath.has(path)) byPath.set(path, parsePath(path));
    }
  }
  // Block editor components register through the same map, so the editor
  // bundle loads a contributed block's inspector without a hand-written
  // import -- the same guarantee admin contributions already have.
  for (const path of collectBlockEditorComponentPaths(plugins)) {
    if (!byPath.has(path)) byPath.set(path, parsePath(path));
  }

  if (byPath.size === 0) {
    return `${HEADER}\n\nexport {};\n`;
  }

  const parsed = Array.from(byPath.values());
  const modules = Array.from(new Set(parsed.map(p => p.module))).sort();
  const alias = new Map<string, string>();
  modules.forEach((m, i) => alias.set(m, `_p${i}`));

  const lines: string[] = [HEADER, ""];
  lines.push('import { registerComponents } from "@nextlyhq/admin";');
  for (const m of modules) {
    lines.push(`import * as ${alias.get(m)} from "${m}";`);
  }
  lines.push("");
  lines.push("registerComponents({");
  for (const p of parsed.sort((a, b) => a.path.localeCompare(b.path))) {
    lines.push(
      `  ${JSON.stringify(p.path)}: ${alias.get(p.module)}.${p.member},`
    );
  }
  lines.push("});");
  lines.push("");
  return lines.join("\n");
}

/**
 * Decide whether to emit a component import map and where. Returns `null` when
 * no enabled plugin contributes admin components (nothing to register) — the
 * caller then writes no file. The map is placed alongside the generated types
 * file so it ships with the app; importing it self-registers the components
 * (it calls `registerComponents` from `@nextlyhq/admin`). Pure — no IO.
 */
export function buildImportMapArtifact(
  plugins: PluginDefinition[],
  typesOutputPath: string
): { path: string; code: string } | null {
  const hasComponents =
    plugins.some(p => collectAdminComponentPaths(p).length > 0) ||
    collectBlockEditorComponentPaths(plugins).length > 0;
  if (!hasComponents) return null;

  return {
    path: join(dirname(typesOutputPath), COMPONENT_IMPORT_MAP_FILENAME),
    code: buildComponentImportMap(plugins),
  };
}
