#!/usr/bin/env bash
set -euo pipefail

# Generated by fallow setup-hooks.
# Installer version: 3.15.0
# Requires bash and node. On Windows run via git-bash or WSL.
# Blocks Claude Code git commit and git push when fallow audit returns verdict fail.
# Runtime errors fail open with a single stderr notice so skips stay visible.
# Set FALLOW_GATE_DEBUG=1 to also log when a command is skipped because it is
# not classified as a git commit or push.
#
# VENDORED, and deliberately no longer what `fallow hooks install` emits.
# The generated script reads JSON with `jq` and compares versions with
# `sort -V`. Neither is available by default on a contributor machine here:
# `jq` is not a dependency of this repo, and BSD `sort` has no `-V`, so on
# macOS the version check aborts the hook under `set -euo pipefail`. Both are
# done with node below, which every contributor already has — `package.json`
# requires it and nothing in this repo runs without it.
#
# Re-running `fallow hooks install --target agent` OVERWRITES this file and
# silently reintroduces both. Re-apply this version if that happens.
#
# Version floor (FALLOW_GATE_MIN_VERSION, default 2.85.0). The gate passes
# --gate-marker agent (added in v2.85.0) so Impact can record containment;
# older binaries reject the flag entirely, which would make every audit fail
# open. The floor also covers the older uncommitted-changes inclusion fix
# (aabb8e1b, v2.46.0). Set the env var to the empty string to disable.
# The floor is compared numerically on major.minor.patch by node, below. A
# prerelease suffix is IGNORED rather than ordered: the floor exists to reject
# binaries too old to accept `--gate-marker`, and a prerelease of a
# high-enough version accepts it.

if ! command -v node >/dev/null 2>&1; then
  echo "fallow-gate: node not on PATH, skipping audit." >&2
  echo "  CI runs the same analysis on your pull request." >&2
  exit 0
fi

# One field out of the JSON document on STDIN, by dotted path.
# $1 = dotted path, $2 = value when the field is absent, null, or the document
# does not parse. Reads stdin rather than a named file so no caller has to make
# a temporary one, and so an early exit cannot strand it.
json_field() {
  node -e '
    const fs = require("fs");
    const [path, fallback = ""] = process.argv.slice(1);
    let value;
    try {
      value = JSON.parse(fs.readFileSync(0, "utf8"));
    } catch {
      process.stdout.write(fallback);
      process.exit(0);
    }
    for (const key of path.split(".")) value = value?.[key];
    process.stdout.write(
      value === undefined || value === null ? fallback : String(value)
    );
  ' "$1" "${2-}"
}

INPUT="$(cat)"
CMD="$(printf '%s' "$INPUT" | json_field tool_input.command)"

# Tokenize instead of matching one regex so git-level options between `git`
# and the subcommand (git -c k=v commit, git -C dir push, git --no-pager
# commit, git --git-dir=/x push) still route into the audit, while subcommand
# lookalikes in arguments (git log commit-message.txt) do not. See issue #2106.
is_git_write_command() {
  local cmd="$1" segment
  # Control operators separate simple commands; each becomes its own line.
  while IFS= read -r segment; do
    # Intentional word splitting; globbing is disabled below.
    # shellcheck disable=SC2086
    set -- $segment
    while [ "$#" -gt 0 ]; do
      if [ "$1" != "git" ]; then
        shift
        continue
      fi
      shift
      while [ "$#" -gt 0 ]; do
        case "$1" in
          commit | push)
            return 0
            ;;
          -c | -C | --git-dir | --work-tree | --namespace | --config-env | --super-prefix | --exec-path | --list-cmds | --attr-source)
            # Global option whose value arrives as the next word.
            shift
            [ "$#" -gt 0 ] && shift
            ;;
          -*)
            # Value-less global option (--no-pager) or inline-value form
            # (--git-dir=/x, -cuser.name=x).
            shift
            ;;
          *)
            # A different subcommand; resume scanning for a later `git` word.
            break
            ;;
        esac
      done
    done
  done < <(printf '%s\n' "$cmd" | tr ';|&()' '\n\n\n\n\n')
  return 1
}

set -f
if is_git_write_command "$CMD"; then
  GIT_WRITE=1
else
  GIT_WRITE=0
fi
set +f
if [ "$GIT_WRITE" -eq 0 ]; then
  if [ -n "${FALLOW_GATE_DEBUG:-}" ]; then
    echo "fallow-gate: not a git commit/push, skipping audit." >&2
  fi
  exit 0
fi

if command -v fallow >/dev/null 2>&1; then
  RUNNER=(fallow)
  BIN_DESC="$(command -v fallow)"
elif command -v npx >/dev/null 2>&1 && VER_PROBE="$(npx --no-install fallow --version 2>/dev/null || true)" && [[ "$VER_PROBE" == fallow* ]]; then
  RUNNER=(npx --no-install fallow)
  BIN_DESC="npx --no-install fallow"
else
  echo "fallow-gate: fallow binary not found (tried PATH and npx --no-install), skipping audit." >&2
  exit 0
fi

VERSION_RAW="$("${RUNNER[@]}" --version 2>/dev/null || true)"
# First line only. `fallow --version` prints a second `verified: ...` line, and
# the trims below cut at a SPACE, not a newline, so without this the patch digit
# arrives fused to that line and parses as 0 — reading 3.15.2 as 3.15.0.
VERSION="${VERSION_RAW%%$'\n'*}"
VERSION="${VERSION#fallow }"
VERSION="${VERSION%% *}"

MIN_VERSION="${FALLOW_GATE_MIN_VERSION-2.85.0}"
if [ -n "$MIN_VERSION" ] && [ -n "$VERSION" ]; then
  # Numeric compare on major.minor.patch, so this works on macOS too.
  if node -e '
    const parse = v => v.split("-")[0].split(".").map(part => Number(part) || 0);
    const [min, cur] = [parse(process.argv[1]), parse(process.argv[2])];
    for (let i = 0; i < 3; i++) {
      const [a, b] = [cur[i] || 0, min[i] || 0];
      if (a !== b) process.exit(a < b ? 0 : 1);
    }
    process.exit(1);
  ' "$MIN_VERSION" "$VERSION"; then
    {
      echo "fallow-gate: blocked: $BIN_DESC is fallow $VERSION, below required $MIN_VERSION."
      echo "fallow-gate: older binaries reject the --gate-marker flag this gate passes"
      echo "fallow-gate: (added in fallow v2.85.0), so the audit cannot run."
      echo "fallow-gate: upgrade the fallow on PATH (e.g. npm install -g fallow@latest or"
      echo "fallow-gate: cargo install fallow-cli), or set FALLOW_GATE_MIN_VERSION= to disable."
    } >&2
    exit 2
  fi
fi

TMP_JSON="$(mktemp)"
TMP_ERR="$(mktemp)"
cleanup() {
  rm -f "$TMP_JSON" "$TMP_ERR"
}
trap cleanup EXIT

if "${RUNNER[@]}" audit --format json --quiet --explain --gate-marker agent >"$TMP_JSON" 2>"$TMP_ERR"; then
  STATUS=0
else
  STATUS=$?
fi

VERDICT="$(json_field verdict <"$TMP_JSON")"
IS_ERROR="$(json_field error false <"$TMP_JSON")"

if [ "$VERDICT" = "fail" ]; then
  echo "fallow-gate: blocked by fallow ${VERSION:-unknown} at $BIN_DESC" >&2
  cat "$TMP_JSON" >&2
  exit 2
fi

if [ "$STATUS" -eq 2 ] || [ "$IS_ERROR" = "true" ]; then
  MSG="$(json_field message <"$TMP_JSON")"
  if [ -n "$MSG" ]; then
    echo "fallow-gate: fallow audit runtime error ($MSG), skipping." >&2
  else
    echo "fallow-gate: fallow audit runtime error, skipping." >&2
  fi
  exit 0
fi

if [ "$STATUS" -ne 0 ]; then
  ERR_LINE="$(sed -n '1p' "$TMP_ERR" 2>/dev/null || true)"
  if [ -n "$ERR_LINE" ]; then
    echo "fallow-gate: fallow audit exited $STATUS ($ERR_LINE), skipping." >&2
  else
    echo "fallow-gate: fallow audit exited $STATUS, skipping." >&2
  fi
  exit 0
fi

exit 0
