<!-- nextly:managed:start -->
<!--
  Everything between these markers is generated by create-nextly-app and may be
  replaced when the project is upgraded. Write your own notes OUTSIDE the block:
  anything above or below it is yours and is preserved.
-->

# Agent guide for this Nextly project

A Next.js app with [Nextly](https://nextlyhq.com) for content. The CMS runs
inside this app rather than beside it: same server, same database, no separate
service to start.

## Where things are

| path                   | what it is                                                         |
| ---------------------- | ------------------------------------------------------------------ |
| `nextly.config.ts`     | the config the whole app boots from — collections, database, admin |
| `src/collections/`     | code-first collection definitions, when this project uses them     |
| `src/app/(frontend)/`  | the public site                                                    |
| `src/app/admin/`       | the admin panel, served at `/admin`                                |
| `migrations/`          | SQL migrations, one file per dialect variant                       |
| `src/types/generated/` | generated types — never edit by hand                               |

## Commands

```bash
npm run dev                  # start Next.js; schema changes apply in-process
npm run build                # migrate, then build
npm run db:setup             # first run: create the schema
npm run db:migrate           # apply pending migrations
npm run db:migrate:status    # what has and has not been applied
npm run db:migrate:fresh     # drop everything and re-run (destructive)
npm run types:generate       # regenerate types after a schema change
```

This project uses **{{databaseDialect}}**.

## Reading content

Content is read through the Direct API, on the server:

```ts
import { getNextly } from "nextly";
import nextlyConfig from "@nextly-config";

const nextly = await getNextly({ config: nextlyConfig });
const posts = await nextly.find({ collection: "posts", limit: 10 });
```

**`find()` returns loosely-typed documents until types are generated.** Without
`npm run types:generate`, `posts.items` is `Record<string, unknown>[]` and a
field access is `unknown`. Generating types makes the slug and the return type
infer, so `posts.items` becomes `Post[]`.

Until then, narrow with a runtime check rather than an assertion — a document
missing a field yields `undefined`, and asserting the type only moves the
failure to where the value is used:

```ts
const slug = typeof doc.slug === "string" ? doc.slug : undefined;
```

## Things that surprise people

- **Users are not a normal collection.** Read them through `nextly.users`, not
  `find({ collection: "users" })`. The users namespace supports pagination and
  `search`; it does not support a `where` filter.
- **Migrations ship one file per dialect.** `0001_x.sql` is Postgres,
  `0001_x.mysql.sql` and `0001_x.sqlite.sql` are the others. The CLI picks the
  variant for the configured dialect; edit all the ones you support.
- **The admin needs a first user.** Visit `/admin` after `npm run dev` and
  complete the setup screen.
- **Cache tags come from `nextly/runtime`.** Wrap reads in `cachedFind` and tag
  them with `nextlyTags(collection)` so a write invalidates the right pages.

## Conventions worth keeping

- Server components read content directly; do not build an API route to fetch
  your own content.
- Regenerate types in the same change as the schema edit that needs them.
- Migrations are append-only once shared. Add a new one rather than editing an
  applied file.

<!-- nextly:managed:end -->
