/**
 * Measured WCAG AA failure counts for every theme lab theme, keyed by id.
 *
 * Generated by scripts/generate-contrast-report.mjs -- do not edit by hand.
 * Covers Nextly originals and tweakcn presets alike: unlike
 * EXPECTED_CONTRAST_FAILURES (themes/index.ts), which records only the themes
 * that miss WCAG AA on purpose, this measures all of them, so a tweakcn
 * preset shows its real score instead of defaulting to "pass".
 *
 * Measured against contrast source `27b7e36e51a4`
 * (packages/ui/src/styles/contrast). These counts are only comparable with
 * others taken against the SAME revision -- the harness deciding them is as
 * much an input as the theme is.
 */
export const CONTRAST_REPORT: Record<string, number> = {
  calm: 0,
  mono: 0,
  sand: 0,
  signal: 0,
  "tweakcn-claude": 34,
  "tweakcn-modern-minimal": 33,
  "tweakcn-twitter": 36,
  "tweakcn-vercel": 1,
  "tweakcn-violet-bloom": 30,
};
