/**
 * Measured WCAG AA failure counts for every theme lab theme, keyed by id.
 *
 * Generated by scripts/generate-contrast-report.mjs -- do not edit by hand.
 * Covers Nextly originals and tweakcn presets alike: unlike
 * EXPECTED_CONTRAST_FAILURES (themes/index.ts), which only records the three
 * Nextly themes that miss WCAG AA on purpose, this measures all of them, so
 * a tweakcn preset shows its real score instead of defaulting to "pass".
 */
export const CONTRAST_REPORT: Record<string, number> = {
  calm: 48,
  mono: 0,
  sand: 0,
  signal: 0,
  "tweakcn-claude": 29,
  "tweakcn-modern-minimal": 28,
  "tweakcn-twitter": 30,
  "tweakcn-vercel": 14,
  "tweakcn-violet-bloom": 24,
};
