/**
 * Config entries reduced to what the diff engine reads.
 *
 * `migrate:create` and `migrate:check` ask the same question of a config —
 * which columns should exist — so they need the same reduction of it. They
 * each carried their own copy with a comment asking the other to be kept in
 * sync; the copies had already drifted in wording, and a field forwarded in
 * one but not the other is a column generated by one command and reported as
 * drift by the other.
 *
 * The per-kind table-name resolver stays a parameter: a collection, a single
 * and a component each normalize their name differently, and that is the only
 * part of the reduction that differs between them.
 *
 * @module domains/schema/migrate-create/config-entities
 */
import type { MinimalConfigEntity } from "./generate";

/** The shape of a config entry before it is reduced. */
interface RawConfigEntity {
  slug: string;
  fields?: {
    name: string;
    type: string;
    required?: boolean;
    hasMany?: boolean;
    relationTo?: string | string[];
    unique?: boolean;
    index?: boolean;
    localized?: boolean;
    dbType?: "integer" | "decimal";
    precision?: number;
    scale?: number;
  }[];
  dbName?: string;
  status?: boolean;
  localized?: boolean;
}

/**
 * Reduce config entries to the shape the diff engine reads.
 *
 * Every forwarded attribute changes a column: `dbType`/`precision`/`scale`
 * decide whether a number is stored as a decimal, `unique`/`index` decide
 * which indexes are desired, `localized` moves a column to the companion
 * table, and `status` adds the lifecycle column. Dropping one here does not
 * fail — it produces a desired state that quietly disagrees with the live one.
 */
export function toMinimalEntities(
  entities: unknown[],
  resolveTableName: (entity: { slug: string; dbName?: string }) => string
): MinimalConfigEntity[] {
  return entities.map(raw => {
    const e = raw as RawConfigEntity;
    const slug = e.slug;
    const fields = (e.fields ?? []).map(f => ({
      name: f.name,
      type: f.type,
      required: f.required,
      hasMany: f.hasMany,
      relationTo: f.relationTo,
      unique: f.unique,
      index: f.index,
      localized: f.localized,
      dbType: f.dbType,
      precision: f.precision,
      scale: f.scale,
    }));
    return {
      slug,
      // Resolved through the same per-kind helper the runtime uses, so a
      // dbName that omits the prefix (a plugin collection with
      // `dbName: "forms"`) still resolves to the table the runtime creates.
      tableName: resolveTableName({ slug, dbName: e.dbName }),
      fields,
      // Components do not carry status; leaving it unset defaults it off
      // inside `buildDesiredSnapshotFromConfig`.
      status: e.status === true,
      localized: e.localized === true,
    };
  });
}
