#!/usr/bin/env node
import { mkdirSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

function ensureDir(path: string) {
  if (!existsSync(path)) {
    mkdirSync(path, { recursive: true });
  }
}

function writeFileIfMissing(path: string, content: string) {
  if (!existsSync(path)) {
    writeFileSync(path, content, { encoding: "utf8" });
    console.log(`✔ Created ${path}`);
  } else {
    console.log(`⏩ Skipped ${path} (already exists)`);
  }
}

function scaffoldAdminApp(targetRoot: string) {
  // App Router structure
  const appAdminRoot = join(targetRoot, "src", "app", "admin");
  const appCatchAllDir = join(appAdminRoot, "[[...params]]");
  const appApiCatchAllDir = join(appAdminRoot, "api", "[[...params]]");
  const appApiHealthDir = join(appAdminRoot, "api", "health");
  const libDir = join(targetRoot, "src", "lib");

  ensureDir(appCatchAllDir);
  ensureDir(appApiCatchAllDir);
  ensureDir(appApiHealthDir);
  ensureDir(libDir);

  const appPageFile = join(appCatchAllDir, "page.tsx");
  const appRouteFile = join(appApiCatchAllDir, "route.ts");
  const healthRouteFile = join(appApiHealthDir, "route.ts");
  const dbInitFile = join(libDir, "db-init.ts");
  const envExampleFile = join(targetRoot, ".env.example");

  // Exact contents provided by the dev app for page.tsx
  const pageContent = `"use client";

import "@nextly/admin/styles.css";
import { RootLayout } from "@nextly/admin";

export default function AdminPage() {
  return <RootLayout />;
}
`;

  // Updated route.ts with auto-initialization
  const routeContent = `// Imported from \`@revnixhq/nextly/runtime\` so the Next.js-coupled
// handler factory doesn't leak into Node-only code paths. See task 24
// stage 1.
import { createDynamicHandlers } from "@revnixhq/nextly/runtime";
import { getOrInitializeDatabase } from "@admin/lib/db-init";

// Initialize database on first request (cached after first run)
await getOrInitializeDatabase();

const handlers = createDynamicHandlers();

export const GET = handlers.GET;
export const POST = handlers.POST;
export const PUT = handlers.PUT;
export const PATCH = handlers.PATCH;
export const DELETE = handlers.DELETE;
export const OPTIONS = handlers.OPTIONS;
`;

  // Database initialization file
  const dbInitContent = `/**
 * Database initialization with automatic migration and seeding
 * This file is auto-generated by @nextly/admin CLI
 *
 * Customize this file to adjust your database setup:
 * - Enable/disable seeders
 * - Add custom initialization logic
 * - Configure error handling
 */

import { initDatabase, type DatabaseAdapter } from "@revnixhq/nextly";

// Cache the database adapter to avoid re-initialization
let dbAdapter: DatabaseAdapter | null = null;
let initializationPromise: Promise<DatabaseAdapter> | null = null;

/**
 * Get or initialize the database connection
 * Ensures migrations and seeders run only once
 *
 * @returns Promise<DatabaseAdapter> - The initialized database adapter
 * @throws Error if initialization fails
 */
export async function getOrInitializeDatabase(): Promise<DatabaseAdapter> {
  // Return cached adapter if already initialized
  if (dbAdapter) {
    return dbAdapter;
  }

  // Return ongoing initialization if in progress
  if (initializationPromise) {
    return initializationPromise;
  }

  // Start new initialization
  initializationPromise = (async () => {
    try {
      console.log("Initializing database...");

      const result = await initDatabase({
        runMigrations: true,
        runSeeders: true, // Set to false to disable auto-seeding
        silentSeeders: false, // Set to true to hide seeder logs
        onSuccess: ({ migration, seeder }) => {
          console.log("Database initialized successfully");
          console.log(\`Migrations: \${migration.applied.length || 1} applied\`);
          if (seeder) {
            console.log(\` Seeds: \${seeder.created} created, \${seeder.skipped} skipped\`);
          }
        },
        onError: (error) => {
          console.error(" Database initialization failed:", error.message);
        },
      });

      if (!result.success) {
        throw new Error(\`Database initialization failed: \${result.error}\`);
      }

      // Cache the adapter
      dbAdapter = result.adapter;
      return dbAdapter;
    } catch (error) {
      // Clear the promise so retry is possible
      initializationPromise = null;
      throw error;
    }
  })();

  return initializationPromise;
}

/**
 * Get the cached database adapter
 * Throws if database hasn't been initialized yet
 *
 * Use this for subsequent requests after initialization
 */
export function getDatabaseAdapter(): DatabaseAdapter {
  if (!dbAdapter) {
    throw new Error("Database not initialized. Call getOrInitializeDatabase() first.");
  }
  return dbAdapter;
}

/**
 * Reset the database connection (useful for testing)
 */
export async function resetDatabaseConnection(): Promise<void> {
  if (dbAdapter) {
    await dbAdapter.disconnect();
    dbAdapter = null;
    initializationPromise = null;
  }
}
`;

  // .env.example template
  const envExampleContent = `# Database Configuration
# Required for @nextly/admin and nextly packages

# Database dialect: "postgresql" or "mysql"
DB_DIALECT=postgresql

# Database connection URL
# PostgreSQL example:
DATABASE_URL=postgresql://user:password@localhost:5432/mydb

# MySQL example:
# DATABASE_URL=mysql://user:password@localhost:3306/mydb

# Optional: Database connection pool settings
DB_POOL_MAX=10
DB_CONNECTION_TIMEOUT=30000
`;

  // Health check endpoint
  const healthRouteContent = `import { NextResponse } from "next/server";
import { getDatabaseAdapter } from "@admin/lib/db-init";
import { healthCheck } from "@revnixhq/nextly";

/**
 * GET /admin/api/health
 * Check database connection and initialization status
 */
export async function GET() {
  try {
    const adapter = getDatabaseAdapter();
    const health = await healthCheck(adapter);

    return NextResponse.json({
      status: "healthy",
      database: {
        connected: health.connected,
        dialect: health.dialect,
        ...health.details,
      },
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    return NextResponse.json(
      {
        status: "unhealthy",
        error: error instanceof Error ? error.message : "Unknown error",
        timestamp: new Date().toISOString(),
      },
      { status: 503 }
    );
  }
}
`;

  // Write all files
  writeFileIfMissing(appPageFile, pageContent);
  writeFileIfMissing(appRouteFile, routeContent);
  writeFileIfMissing(healthRouteFile, healthRouteContent);
  writeFileIfMissing(dbInitFile, dbInitContent);
  writeFileIfMissing(envExampleFile, envExampleContent);
}

function resolveDevAppRoot(): string {
  return process.cwd(); // default to current project root
}

function main() {
  const args = process.argv.slice(2);
  // Support either positional <targetRoot> or --dir=<targetRoot>
  const firstPositional = args.find(a => !a.startsWith("-"));
  const dirArg = args.find(a => a.startsWith("--dir="));
  const targetApp =
    firstPositional || (dirArg ? dirArg.split("=")[1] : undefined);

  const resolvedTarget =
    targetApp && existsSync(targetApp) ? targetApp : resolveDevAppRoot();

  console.log("\n Setting up Admin App with Database...\n");

  ensureDir(join(resolvedTarget, "src", "app"));
  scaffoldAdminApp(resolvedTarget);

  console.log("\n Setup complete!\n");
  console.log("Files created:");
  console.log(
    `   • ${join(resolvedTarget, "src", "app", "admin", "[[...params]]", "page.tsx")}`
  );
  console.log(
    `   • ${join(resolvedTarget, "src", "app", "admin", "api", "[[...params]]", "route.ts")}`
  );
  console.log(
    `   • ${join(resolvedTarget, "src", "app", "admin", "api", "health", "route.ts")}`
  );
  console.log(`   • ${join(resolvedTarget, "src", "lib", "db-init.ts")}`);
  console.log(`   • ${join(resolvedTarget, ".env.example")}`);

  console.log("\n📋 Next steps:");
  console.log("   1. Copy .env.example to .env and configure your database");
  console.log("   2. Start your Next.js app: npm run dev");
  console.log("   3. Access /admin - database will auto-initialize!");
  console.log("   4. Check health: GET /admin/api/health");
  console.log("\n Tips:");
  console.log("   • Customize src/lib/db-init.ts to adjust seeding behavior");
  console.log("   • Set runSeeders: false to skip auto-seeding");
  console.log("   • Use /admin/api/health to verify database status\n");
}

main();
