"use client";

/**
 * useBuilderFieldActions — the operations a schema-builder page performs on its
 * own field list, independent of which kind of entity it is editing.
 *
 * `useFieldBuilder` owns the field state; this owns the three decisions the
 * pages make about that state and had been making identically three times
 * over: what a duplicated field is named, what a drag means, and which fields
 * count as the user's.
 */
import type { DragEndEvent } from "@dnd-kit/core";
import { arrayMove } from "@dnd-kit/sortable";
import { useCallback } from "react";

import type {
  BuilderField,
  BuilderFieldsApi,
} from "@admin/components/features/schema-builder/types";
import { toast } from "@admin/components/ui";
import {
  convertToFieldDefinition,
  findFieldById,
  findParentContainerId,
  reorderNestedFields,
  SYSTEM_FIELD_NAMES,
} from "@admin/lib/builder";
import {
  builderDropAccepted,
  builderRowIndex,
  builderRows,
} from "@admin/lib/builder/builder-rows";
import { nextDuplicateName } from "@admin/lib/builder/duplicate-field-name";
import type { FieldDefinition } from "@admin/types/collection";

/**
 * Apply a top-level move, which is expressed against ROWS rather than fields:
 * the field list packs fields into rows by width, so a row's new position has
 * to be applied to that layout and flattened back into a field order. System
 * fields are not packed and stay ahead of the result.
 *
 * Returns null when the ids are not row ids, which is every other drag.
 */
function reorderRows(
  fields: BuilderField[],
  activeId: string,
  overId: string
): BuilderField[] | null {
  const oldIdx = builderRowIndex(activeId);
  const newIdx = builderRowIndex(overId);
  if (oldIdx === undefined || newIdx === undefined) return null;

  // 🔴 The SAME packing the field list draws from. Packed here with different
  // inputs -- hidden fields kept, a repeater at its stored width -- the index
  // the reader dragged named a different row from the one this moved.
  const systemFields = fields.filter(f => f.isSystem);
  // Hidden fields take no row and are not drawn, so a reorder cannot place
  // them; they are carried through after the visible fields rather than lost.
  const hiddenFields = fields.filter(
    f => !f.isSystem && f.admin?.hidden === true
  );
  const rows = builderRows(fields);
  // `arrayMove` splices without checking, so an index outside the packed rows
  // moves `undefined` into the list and the flatMap below reads `_field` off
  // it. The ids are generated by the field list, so this should not arise —
  // which makes it a cheap assertion over values already in hand rather than
  // a reason to trust them.
  const inRange = (i: number) => i >= 0 && i < rows.length;
  if (!inRange(oldIdx) || !inRange(newIdx)) return null;

  const reordered = arrayMove(rows, oldIdx, newIdx).flatMap(row =>
    row.map(r => r._field)
  );
  return [...systemFields, ...reordered, ...hiddenFields];
}

export interface UseBuilderFieldActionsReturn {
  /** Clone a field beside itself, under the next free name. */
  handleDuplicateField: (fieldId: string) => void;
  /** Apply a drag from the field list. */
  handleRowDragEnd: (event: DragEndEvent) => void;
  /**
   * The user's fields as field definitions, or null when they do not validate
   * — in which case the reason has already been shown as a toast.
   */
  getValidatedFields: () => FieldDefinition[] | null;
}

export function useBuilderFieldActions(
  builder: BuilderFieldsApi
): UseBuilderFieldActionsReturn {
  const handleDuplicateField = useCallback(
    (fieldId: string) => {
      // Duplicate is reachable from nested rows as well as top-level ones, so
      // locate the source and its container first. `takenNames` is the sibling
      // list rather than every field, which lets a nested field and a
      // top-level one carry the same name.
      const source = findFieldById(builder.fields, fieldId);
      if (!source) return;
      const parent = findParentContainerId(builder.fields, fieldId);
      const siblings = parent
        ? (findFieldById(builder.fields, parent.containerId)?.fields ?? [])
        : builder.fields;
      const takenNames = siblings.map(f => f.name);
      const duplicate: BuilderField = {
        ...source,
        id: `field_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`,
        name: nextDuplicateName(source.name, takenNames),
      };
      if (parent) {
        builder.handleNestedFieldAdd(parent.containerId, duplicate);
      } else {
        builder.setFields([...builder.fields, duplicate]);
      }
    },
    [builder]
  );

  // The field list speaks two drag vocabularies: a nested child drags by field
  // id and sorts within its own container, while a top-level field drags by the
  // index of the row it was packed into.
  const handleRowDragEnd = useCallback(
    (event: DragEndEvent) => {
      const { active, over } = event;
      if (!over) return;
      const activeId = String(active.id);
      const overId = String(over.id);
      // The ONE acceptance rule, shared with the drag announcements so what
      // the reader is told matches what happens: a refused drop is refused
      // here and described as unchanged there.
      if (!builderDropAccepted(builder.fields, activeId, overId)) return;

      if (builderRowIndex(activeId) === undefined) {
        builder.setFields(prev => reorderNestedFields(prev, activeId, overId));
        return;
      }

      const reordered = reorderRows(builder.fields, activeId, overId);
      if (reordered) builder.handleFieldsReorder(reordered);
    },
    [builder]
  );

  const getValidatedFields = useCallback((): FieldDefinition[] | null => {
    const userFields = builder.fields.filter(
      f => !f.isSystem && !SYSTEM_FIELD_NAMES.includes(f.name)
    );
    const validation = builder.validateFields(userFields);
    if (!validation.valid) {
      // `errorMessage` is optional on the result, so a validator reporting
      // invalid without saying why would raise an empty toast — a refusal the
      // user cannot act on and cannot tell apart from a UI glitch.
      toast.error(validation.errorMessage || "Some fields are not valid yet.");
      return null;
    }
    return userFields.map(convertToFieldDefinition);
  }, [builder]);

  return { handleDuplicateField, handleRowDragEnd, getValidatedFields };
}
