import crypto from "crypto";
import path from "path";

import fs from "fs-extra";

import type { DatabaseConfig, EnvGenerationResult } from "../types";

/**
 * Generate a cryptographically secure NEXTLY_SECRET.
 */
function generateNextlySecret(): string {
  return crypto.randomBytes(32).toString("base64");
}

/**
 * Whether a `.env` already mentions the diagnostics setting.
 *
 * Anchored to the start of a line and to the `=` that follows, so a DIFFERENT
 * variable whose name merely starts the same way -- `NEXTLY_DEV_DIAGNOSTICS_URL`
 * and the like -- does not read as this one and silently suppress the note. A
 * commented form counts: the note is what is being added, and adding a second
 * copy of it below the first would be noise rather than help.
 *
 * `export KEY=value` counts too. dotenv accepts it so the same file can be
 * sourced by a shell, and a project written that way would otherwise be told
 * the setting is absent and handed a duplicate block.
 *
 * The horizontal-space classes are `[ \t]`, not `\s`. Under the `m` flag `\s`
 * matches newlines, so the two around an optional `#` can each consume the
 * blank lines an `.env` is full of, and the engine retries that from every
 * line -- quadratic work on a file that simply does not contain the key.
 * Confining them to the current line is what keeps the scan linear.
 */
function mentionsDiagnostics(env: string): boolean {
  return /^[ \t]*(?:#[ \t]*)?(?:export[ \t]+)?NEXTLY_DEV_DIAGNOSTICS[ \t]*=/m.test(
    env
  );
}

/**
 * The diagnostics note, shared by the full template and the append-only path.
 *
 * One definition because the two paths write it in different situations and a
 * second copy would let them describe the same setting differently.
 */
const DIAGNOSTICS_BLOCK = `# Development diagnostics (opt-in)
# Uncomment to add a _devDiagnostics field to error responses, carrying the
# log context of an error and the underlying cause, so a failure names itself
# while you build instead of only in the server log.
#
# Left commented on purpose. It is the SECOND of two independent signals — the
# first is NODE_ENV — and the second exists precisely because NODE_ENV is a
# runtime value a deployment can carry by mistake. A default that ships in this
# file would be true in exactly that case, which is the one it guards against.
# NEXTLY_DEV_DIAGNOSTICS=1
`;

/**
 * Generate the environment file template.
 */
function getEnvTemplate(database: DatabaseConfig): string {
  return `# Nextly Configuration
# Generated by create-nextly-app

# Database Configuration
DB_DIALECT=${database.type}
DATABASE_URL=${database.envExample}

# Authentication (auto-generated, change if needed)
NEXTLY_SECRET=${generateNextlySecret()}

# Where the Nextly app itself lives: the admin, the API, and the origin its
# emails and preview links point at.
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Where READERS find the public site. Used for canonical links, Open Graph
# tags, the sitemap and RSS. Set it when the public site is served from a
# different origin than the app above; otherwise the app's origin is used.
# NEXT_PUBLIC_SITE_URL=https://example.com

${DIAGNOSTICS_BLOCK}`;
}

/**
 * Generate or update the .env file with Nextly configuration.
 *
 * @param cwd - Working directory
 * @param database - Database configuration
 */
export async function generateEnv(
  cwd: string,
  database: DatabaseConfig
): Promise<EnvGenerationResult> {
  const envPath = path.join(cwd, ".env");
  const envExamplePath = path.join(cwd, ".env.example");

  const envContent = getEnvTemplate(database);

  // Always create/update .env.example
  await fs.writeFile(envExamplePath, envContent, "utf-8");

  // Check if .env exists
  if (await fs.pathExists(envPath)) {
    // Append Nextly config if not present
    const existingEnv = await fs.readFile(envPath, "utf-8");
    if (!existingEnv.includes("DATABASE_URL")) {
      await fs.appendFile(envPath, "\n" + envContent, "utf-8");
      return { created: false, updated: true };
    }
    // An install into a project that already has a configured .env still gets
    // the diagnostics note, keyed on its own absence rather than on
    // DATABASE_URL. Sharing that condition meant the setting only ever reached
    // brand-new apps, so the file the developer actually runs never mentioned
    // it while .env.example did.
    if (!mentionsDiagnostics(existingEnv)) {
      await fs.appendFile(envPath, "\n" + DIAGNOSTICS_BLOCK, "utf-8");
      return { created: false, updated: true };
    }
    return { created: false, updated: false };
  }

  // Create new .env
  await fs.writeFile(envPath, envContent, "utf-8");
  return { created: true, updated: false };
}
