import crypto from "crypto";
import path from "path";

import fs from "fs-extra";

import type { DatabaseConfig, EnvGenerationResult } from "../types";

/**
 * Generate a cryptographically secure NEXTLY_SECRET.
 */
function generateNextlySecret(): string {
  return crypto.randomBytes(32).toString("base64");
}

/**
 * Generate the environment file template.
 */
function getEnvTemplate(database: DatabaseConfig): string {
  return `# Nextly Configuration
# Generated by create-nextly-app

# Database Configuration
DB_DIALECT=${database.type}
DATABASE_URL=${database.envExample}

# Authentication (auto-generated, change if needed)
NEXTLY_SECRET=${generateNextlySecret()}

# Application URL
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Development diagnostics (development only)
# Adds a _devDiagnostics field to error responses carrying the error's log
# context and the underlying cause, so a failure names itself while you build
# instead of only in the server log.
#
# Ignored unless NODE_ENV is development. Two signals are required because
# nextly ships pre-built and stays external to your build, so NODE_ENV is a
# runtime value a production deployment can carry by mistake — this flag alone
# can never turn the detail on there. Safe to leave set.
NEXTLY_DEV_DIAGNOSTICS=1
`;
}

/**
 * Generate or update the .env file with Nextly configuration.
 *
 * @param cwd - Working directory
 * @param database - Database configuration
 */
export async function generateEnv(
  cwd: string,
  database: DatabaseConfig
): Promise<EnvGenerationResult> {
  const envPath = path.join(cwd, ".env");
  const envExamplePath = path.join(cwd, ".env.example");

  const envContent = getEnvTemplate(database);

  // Always create/update .env.example
  await fs.writeFile(envExamplePath, envContent, "utf-8");

  // Check if .env exists
  if (await fs.pathExists(envPath)) {
    // Append Nextly config if not present
    const existingEnv = await fs.readFile(envPath, "utf-8");
    if (!existingEnv.includes("DATABASE_URL")) {
      await fs.appendFile(envPath, "\n" + envContent, "utf-8");
      return { created: false, updated: true };
    }
    return { created: false, updated: false };
  }

  // Create new .env
  await fs.writeFile(envPath, envContent, "utf-8");
  return { created: true, updated: false };
}
