import path from "path";

import fs from "fs-extra";

import type { ProjectInfo } from "../types";

/**
 * Create the types directory structure for generated TypeScript types.
 * This mirrors what `nextly init` does - creates the directory and a placeholder file.
 * The actual types are generated when running `next dev` (which boots Nextly
 * and emits types lazily) or `npx @revnixhq/nextly generate:types`.
 */
export async function generateTypesDirectory(
  cwd: string,
  projectInfo: ProjectInfo
): Promise<void> {
  const baseDir = projectInfo.srcDir ? "src" : ".";
  const typesDir = path.join(cwd, baseDir, "types", "generated");

  // Create the types/generated directory
  await fs.ensureDir(typesDir);

  // Create a .gitkeep file to ensure the directory is tracked
  const gitkeepPath = path.join(typesDir, ".gitkeep");
  if (!(await fs.pathExists(gitkeepPath))) {
    await fs.writeFile(gitkeepPath, "", "utf-8");
  }

  // Create a placeholder types file with instructions
  const placeholderPath = path.join(typesDir, "nextly-types.ts");
  if (!(await fs.pathExists(placeholderPath))) {
    const placeholderContent = `/**
 * Nextly Generated Types
 *
 * This file will be auto-generated when you run:
 *   next dev          (Nextly emits types on first boot)
 *   npx @revnixhq/nextly generate:types
 *
 * Do not edit this file manually - it will be overwritten.
 */

// Types will be generated here after running next dev
export {};
`;
    await fs.writeFile(placeholderPath, placeholderContent, "utf-8");
  }
}
