/**
 * The modal scrim is a token, and stays one.
 *
 * It was written inline as `bg-black/80` — identical in both modes, at four
 * different strengths across six components. That is drift rather than intent,
 * and it is invisible to every token check the package has, because a literal
 * in a class name is not a token to check.
 *
 * Scope note: this reads sibling packages' source, which `packages/ui/turbo.json`
 * declares as inputs to this package's `test` task, so a change in a scanned
 * package invalidates the cached result. Same arrangement as the alpha-utility
 * call-site guard beside it.
 */
import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import preset from "../../tailwind-preset";
import { compositeOver, contrastRatio, type Rgb } from "../contrast/color";
import { parseThemeTokens } from "../contrast/parse-theme";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "../../../../..");
const css = readFileSync(resolve(here, "../theme.css"), "utf8");
const { light, dark } = parseThemeTokens(css);

const OVERLAY_TOKENS = [
  "--nx-overlay",
  "--nx-overlay-soft",
  "--nx-overlay-strong",
];

/** Every `.tsx` under a package's `src`, minus tests. */
function sources(pkg: string): string[] {
  const root = join(repo, "packages", pkg, "src");
  const out: string[] = [];
  const visit = (dir: string): void => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) {
        visit(full);
        continue;
      }
      if (entry.endsWith(".tsx") && !entry.includes(".test.")) out.push(full);
    }
  };
  visit(root);
  return out;
}

describe("overlay scrim token", () => {
  it("is defined in both modes", () => {
    for (const token of OVERLAY_TOKENS) {
      expect(light.get(token), `${token} missing from :root`).toBeDefined();
      expect(dark.get(token), `${token} missing from .dark`).toBeDefined();
    }
  });

  it("differs between the modes, which is the reason it is a token", () => {
    // A scrim composites over what is beneath it, and what is beneath it is
    // white in one mode and near-black in the other. One value for both is a
    // literal with extra steps, and that is exactly what the inline
    // `bg-black/80` was.
    for (const token of OVERLAY_TOKENS) {
      expect(dark.get(token)).not.toBe(light.get(token));
    }
  });

  it("is generated by the v3 preset as well as the v4 theme", () => {
    // `@nextlyhq/ui/tailwind-preset` is the documented Tailwind v3 path and
    // reads none of the `@theme` block. Without a colour entry there, v3
    // generates no rule for `bg-overlay` at all, so a backdrop is transparent
    // rather than merely unthemed — a failure the v4 build cannot show.
    const colors = preset.theme?.extend?.colors as
      | Record<string, unknown>
      | undefined;
    expect(colors?.["overlay"]).toBe("var(--nx-overlay)");
    expect(colors?.["overlay-soft"]).toBe("var(--nx-overlay-soft)");
  });

  it("keeps text on the read-on scrim above AA", () => {
    // `--nx-overlay` sits UNDER a modal, which brings its own surface for text.
    // `--nx-overlay-strong` is the one a full-screen state screen writes its
    // message directly onto, so it is the one that has to carry contrast. The
    // worst case is light mode: the scrim composites over a white page and so
    // lands lighter than the same idea does in dark.
    const WHITE: Rgb = { r: 1, g: 1, b: 1, alpha: 1 };
    const alphaOf = (token: string): number => {
      const value = light.get(token) ?? "";
      const match = /\/\s*([0-9.]+)\s*\)/.exec(value);
      expect(match, `${token} should carry an alpha: ${value}`).not.toBeNull();
      return Number(match?.[1]);
    };

    const scrim = compositeOver(
      { r: 0, g: 0, b: 0, alpha: alphaOf("--nx-overlay-strong") },
      WHITE
    );
    // The muted detail line the restart overlay renders, which is the smallest
    // text any scrim in the admin carries.
    const muted = compositeOver({ ...WHITE, alpha: 0.6 }, scrim);
    expect(contrastRatio(muted, scrim)).toBeGreaterThanOrEqual(4.5);
  });

  it("does not put muted text on the see-through scrim", () => {
    // `bg-overlay` is a scrim you look THROUGH: it sits under a modal, which
    // brings its own surface for text. A file that pairs it with muted white
    // text is reading on it instead, and in light mode that composites to a
    // mid-grey no muted white clears AA against. `bg-overlay-strong` exists for
    // that case, so the pairing is the signal rather than the ratio.
    const offenders: string[] = [];
    for (const pkg of ["ui", "admin"]) {
      for (const file of sources(pkg)) {
        const text = readFileSync(file, "utf8");
        // The see-through token exactly — not `-strong`, not `-soft`.
        if (!/\bbg-overlay(?![\w-])/.test(text)) continue;
        if (!/\btext-white\/\d+/.test(text)) continue;
        offenders.push(file.slice(repo.length + 1));
      }
    }
    expect(
      offenders,
      "These pair the see-through scrim with muted white text. Use " +
        `bg-overlay-strong for a surface that carries text:\n${offenders.join("\n")}`
    ).toEqual([]);
  });

  it("is the only way a scrim is written", () => {
    // The call-site half. A token nothing uses does not fix anything, and a
    // literal reintroduced next to it is invisible to the checks above.
    const offenders: string[] = [];
    for (const pkg of ["ui", "admin"]) {
      for (const file of sources(pkg)) {
        const text = readFileSync(file, "utf8");
        for (const m of text.matchAll(
          /\bbg-(?:black|white)\/(?:\[[^\]]*\]|\d+)/g
        )) {
          offenders.push(`${file.slice(repo.length + 1)}: ${m[0]}`);
        }
      }
    }
    expect(
      offenders,
      "A scrim written as a literal is the same colour in light and dark and " +
        "cannot be themed. Use bg-overlay, or bg-overlay-soft over content:\n" +
        offenders.join("\n")
    ).toEqual([]);
  });
});
