/**
 * Which entities are still waiting on a migration that has not run.
 *
 * 🔴 The sweep that records `migration_status = 'applied'` asked only whether
 * the entity's table exists. That is the right evidence for a CREATE and proves
 * nothing for an EDIT: editing a collection in the Schema Builder writes the
 * new fields, sets the row back to `pending` and leaves the physical table
 * untouched — so existence still answers yes, and the row is promoted while the
 * column, status or localization change it is waiting for has not been applied.
 *
 * ## Why the header rather than a shape comparison
 *
 * The tempting evidence is the shape: compare what the row wants against what
 * the migrations produced. Three separate things defeat it, and each was
 * measured rather than supposed.
 *
 * A migration generated by `migrate:create` writes a snapshot of physical
 * TABLES (`{ version, migrationHash, snapshot: { tables } }`); only scaffolded
 * templates carry entity-level `collections` and `singles`. So a shape
 * comparison reading entity snapshots finds nothing at all for exactly the
 * Schema-Builder entities it exists to serve.
 *
 * A status or localization toggle sets the row back to `pending` while leaving
 * its field list identical, so a field comparison reports agreement for a
 * change that has not been applied.
 *
 * And `calculateSchemaHash` folds `SYSTEM_SCHEMA_VERSION` into its input, so a
 * historical snapshot rehashed today appears to contain system columns whose
 * migration has not run.
 *
 * The header answers the question directly instead. Each migration names the
 * entities it changes, `runFileMigrations` records which migrations ran, and a
 * row is waiting exactly when some migration naming its slug has not been
 * applied — no shape, no snapshot format, no version.
 *
 * @module domains/schema/migrate/pending-entities
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";

import type { SupportedDialect } from "@nextlyhq/adapter-drizzle/types";

import {
  discoverMigrationGroups,
  selectVariant,
} from "../../../cli/utils/migration-discovery";
import { parseEntityHeaders } from "../migrate-create/format-file";

import type { IsAppliedFn } from "./snapshot-source";

export interface PendingEntitiesOptions {
  migrationsDir: string;
  /**
   * The dialect whose variant will actually be executed.
   *
   * 🔴 Passed so this reads the SAME file `runFileMigrations` will run.
   * A group can hold a base file and a dialect override with different
   * headers — a legacy base beside a newly annotated `.mysql.sql`, say — and
   * reading the base there names no slug, so the row is promoted while the
   * file that will really run is still outstanding.
   */
  dialect?: SupportedDialect;
  isApplied: IsAppliedFn;
  logger?: { warn?: (msg: string) => void; debug?: (msg: string) => void };
}

/**
 * Entity slugs named by at least one migration the ledger has not recorded as
 * applied, by kind.
 *
 * Field groups are carried even though the sweep's field-group registry has no
 * snapshot evidence of its own: the header names them, so the same rule reaches
 * all three kinds.
 */
export interface PendingEntities {
  collections: Set<string>;
  singles: Set<string>;
  components: Set<string>;
}

/** Nothing is waiting — the shape a caller gets when there is no evidence. */
export function noPendingEntities(): PendingEntities {
  return {
    collections: new Set(),
    singles: new Set(),
    components: new Set(),
  };
}

/**
 * Read every migration's header and collect the slugs the unapplied ones name.
 *
 * 🔴 The ledger is asked about the migration GROUP's base `.sql` name, which is
 * what `runFileMigrations` records for every dialect variant — `0001_x.sql`
 * whether it executed `0001_x.sql` or `0001_x.mysql.sql`. Asking about a
 * variant would report a migration that ran as outstanding, and hold every
 * entity it names back forever.
 *
 * The VARIANT is chosen the way the apply path chooses it, so the header read
 * belongs to the file that will actually run rather than to a sibling that
 * happens to sort first.
 */
export async function readPendingEntities(
  options: PendingEntitiesOptions
): Promise<PendingEntities> {
  const { migrationsDir, dialect, isApplied, logger } = options;
  const pending = noPendingEntities();

  const groups = await discoverMigrationGroups(migrationsDir);

  for (const [baseName, group] of groups) {
    const ledgerFilename = `${baseName}.sql`;
    if (await isApplied(ledgerFilename)) continue;

    // The same chooser the apply path uses, so the header read here belongs
    // to the file that will really be executed.
    const file = selectVariant(group.variants, dialect);
    if (!file) continue;

    let content: string;
    try {
      content = await readFile(join(migrationsDir, file), "utf-8");
    } catch (err) {
      /*
       * A migration whose file cannot be read is left out rather than treated
       * as naming everything. Naming everything would hold every pending row
       * back on an unreadable file, which costs an operator their dashboards
       * for a reason nothing on screen explains; leaving it out restores the
       * previous behaviour for those rows and nothing worse.
       */
      logger?.warn?.(
        `Could not read migration ${file} while checking what is still pending: ${String(err)}`
      );
      continue;
    }

    const named = parseEntityHeaders(content);
    for (const slug of named.collections) pending.collections.add(slug);
    for (const slug of named.singles) pending.singles.add(slug);
    for (const slug of named.components) pending.components.add(slug);
  }

  return pending;
}

/**
 * Whether this row is waiting on a migration that has not run.
 *
 * 🔴 Only a slug NAMED by an unapplied migration is held back. A row nothing
 * names is promoted exactly as before — a code-first collection, an install
 * whose migrations predate scoped headers, an entity whose migrations have all
 * run. Withholding on silence would empty dashboards that work today, which is
 * a worse failure than the one this fixes and is invisible to whoever hits it.
 */
export function isAwaitingMigration(
  record: unknown,
  named: Set<string>
): boolean {
  if (typeof record !== "object" || record === null) return false;
  const { slug } = record as { slug?: unknown };
  if (typeof slug !== "string" || slug === "") return false;
  return named.has(slug);
}
