/**
 * Which entities are still waiting on a migration that has not run.
 *
 * 🔴 The sweep that records `migration_status = 'applied'` asked only whether
 * the entity's table exists. That is the right evidence for a CREATE and proves
 * nothing for an EDIT: editing a collection in the Schema Builder writes the
 * new fields, sets the row back to `pending` and leaves the physical table
 * untouched — so existence still answers yes, and the row is promoted while the
 * column, status or localization change it is waiting for has not been applied.
 *
 * ## Why the header rather than a shape comparison
 *
 * The tempting evidence is the shape: compare what the row wants against what
 * the migrations produced. Three separate things defeat it, and each was
 * measured rather than supposed.
 *
 * A migration generated by `migrate:create` writes a snapshot of physical
 * TABLES (`{ version, migrationHash, snapshot: { tables } }`); only scaffolded
 * templates carry entity-level `collections` and `singles`. So a shape
 * comparison reading entity snapshots finds nothing at all for exactly the
 * Schema-Builder entities it exists to serve.
 *
 * A status or localization toggle sets the row back to `pending` while leaving
 * its field list identical, so a field comparison reports agreement for a
 * change that has not been applied.
 *
 * And `calculateSchemaHash` folds `SYSTEM_SCHEMA_VERSION` into its input, so a
 * historical snapshot rehashed today appears to contain system columns whose
 * migration has not run.
 *
 * The header answers the question directly instead. Each migration names the
 * entities it changes, `runFileMigrations` records which migrations ran, and a
 * row is waiting exactly when some migration naming its slug has not been
 * applied — no shape, no snapshot format, no version.
 *
 * @module domains/schema/migrate/pending-entities
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";

import type { SupportedDialect } from "@nextlyhq/adapter-drizzle/types";

import {
  discoverMigrationGroups,
  selectVariant,
} from "../../../cli/utils/migration-discovery";
import {
  parseEntityHeaders,
  type MigrationEntityHeaders,
} from "../migrate-create/format-file";

import type { IsAppliedFn } from "./snapshot-source";

export interface PendingEntitiesOptions {
  migrationsDir: string;
  /**
   * The dialect whose variant will actually be executed.
   *
   * 🔴 Passed so this reads the SAME file `runFileMigrations` will run.
   * A group can hold a base file and a dialect override with different
   * headers — a legacy base beside a newly annotated `.mysql.sql`, say — and
   * reading the base there names no slug, so the row is promoted while the
   * file that will really run is still outstanding.
   */
  dialect?: SupportedDialect;
  isApplied: IsAppliedFn;
  logger?: { warn?: (msg: string) => void; debug?: (msg: string) => void };
}

/**
 * Entity slugs named by at least one migration the ledger has not recorded as
 * applied, by kind.
 *
 * Field groups are carried even though the sweep's field-group registry has no
 * snapshot evidence of its own: the header names them, so the same rule reaches
 * all three kinds.
 */
export interface PendingEntities {
  collections: Set<string>;
  singles: Set<string>;
  components: Set<string>;
  /**
   * Unapplied migrations that name no entity at all.
   *
   * 🔴 Reported rather than acted on. Two files land here: one from
   * `migrate:create --blank`, which carries no entity header at all — a
   * hand-written `ALTER` for a MySQL nullability change is exactly this — and
   * one generated before headers were scoped, whose header lists the whole
   * config rather than what it changes. Both have unknown scope rather than
   * empty scope, and a row either silently affects is promoted once its old
   * table exists.
   *
   * Withholding every row while one of these is outstanding would be the
   * conservative reading and is worse: it empties every dashboard on the
   * strength of a file nobody has described. So promotion proceeds and the
   * operator is told, which is the only response that neither hides the gap nor
   * punishes the entities it cannot be about.
   */
  unscoped: string[];
}

/** Nothing is waiting — the shape a caller gets when there is no evidence. */
export function noPendingEntities(): PendingEntities {
  return {
    collections: new Set(),
    singles: new Set(),
    components: new Set(),
    unscoped: [],
  };
}

/**
 * Read every migration's header and collect the slugs the unapplied ones name.
 *
 * 🔴 The ledger is asked about the migration GROUP's base `.sql` name, which is
 * what `runFileMigrations` records for every dialect variant — `0001_x.sql`
 * whether it executed `0001_x.sql` or `0001_x.mysql.sql`. Asking about a
 * variant would report a migration that ran as outstanding, and hold every
 * entity it names back forever.
 *
 * The VARIANT is chosen the way the apply path chooses it, so the header read
 * belongs to the file that will actually run rather than to a sibling that
 * happens to sort first.
 */
/** Whether a header named no entity of any kind. */
function namesNothing(named: MigrationEntityHeaders): boolean {
  return (
    named.collections.length === 0 &&
    named.singles.length === 0 &&
    named.components.length === 0
  );
}

/** Fold one migration's named entities into the running set, by kind. */
function absorb(pending: PendingEntities, named: MigrationEntityHeaders): void {
  for (const slug of named.collections) pending.collections.add(slug);
  for (const slug of named.singles) pending.singles.add(slug);
  for (const slug of named.components) pending.components.add(slug);
}

/**
 * The entities one migration file names, or `undefined` when it cannot be read.
 *
 * 🔴 An unreadable file is left OUT rather than treated as naming everything.
 * Naming everything would hold every pending row back on a file nobody can
 * open, which costs an operator their dashboards for a reason nothing on screen
 * explains; leaving it out restores the previous behaviour for those rows and
 * nothing worse.
 */
async function namedEntitiesIn(
  migrationsDir: string,
  file: string,
  logger?: { warn?: (msg: string) => void }
): Promise<MigrationEntityHeaders | undefined> {
  try {
    const content = await readFile(join(migrationsDir, file), "utf-8");
    return parseEntityHeaders(content);
  } catch (err) {
    logger?.warn?.(
      `Could not read migration ${file} while checking what is still pending: ${String(err)}`
    );
    return undefined;
  }
}

export async function readPendingEntities(
  options: PendingEntitiesOptions
): Promise<PendingEntities> {
  const { migrationsDir, dialect, isApplied, logger } = options;
  const pending = noPendingEntities();

  const groups = await discoverMigrationGroups(migrationsDir);

  for (const [baseName, group] of groups) {
    if (await isApplied(`${baseName}.sql`)) continue;

    // The same chooser the apply path uses, so the header read here belongs
    // to the file that will really be executed.
    const file = selectVariant(group.variants, dialect);
    if (!file) continue;

    const named = await namedEntitiesIn(migrationsDir, file, logger);
    if (!named) continue;

    /*
     * 🔴 An UNMARKED file's names are not ownership. Migrations generated
     * before headers were scoped list every entity in the config, so trusting
     * one makes an unrelated old migration hold a collection's row — and its
     * dashboard — until that migration runs. A reader cannot tell a legacy
     * header from a scoped one by looking at it: both are a list of slugs.
     *
     * Treated as unknown scope, which is the same answer a file with no header
     * gets, and reported for the same reason. Unknown promotes; a wrong
     * withhold empties a dashboard with nothing on screen to explain it.
     */
    if (!named.scoped || namesNothing(named)) {
      pending.unscoped.push(file);
      continue;
    }

    absorb(pending, named);
  }

  return pending;
}

/**
 * Whether this row is waiting on a migration that has not run.
 *
 * 🔴 Only a slug NAMED by an unapplied migration is held back. A row nothing
 * names is promoted exactly as before — a code-first collection, an install
 * whose migrations predate scoped headers, an entity whose migrations have all
 * run. Withholding on silence would empty dashboards that work today, which is
 * a worse failure than the one this fixes and is invisible to whoever hits it.
 */
export function isAwaitingMigration(
  record: unknown,
  named: Set<string>
): boolean {
  if (typeof record !== "object" || record === null) return false;
  const { slug } = record as { slug?: unknown };
  if (typeof slug !== "string" || slug === "") return false;
  return named.has(slug);
}
