// What: child-side HTTP endpoints for wrapper <-> child IPC at /__nextly/*.
// Why: the wrapper process owns DDL execution and file watching because it
// runs in plain Node where drizzle-kit/api works reliably. The child (next
// dev) owns HTTP and the admin UI. These endpoints coordinate the two:
// - wrapper POSTs /pending when a code-first change is detected
// - wrapper POSTs /applied after DDL succeeds (before it respawns the child)
// - admin apply-endpoint queues a request via pushApplyRequest, wrapper polls
//   GET /apply-request and later POSTs /apply-result so the admin endpoint
//   can resolve back to the UI

import { randomUUID } from "node:crypto";

import { validateIpcToken } from "../../cli/wrapper/ipc-token.js";
import type {
  AppliedChangePayload,
  ApplyRequest,
  ApplyRequestResult,
  PendingChangePayload,
} from "../../domains/schema/types/ipc-types.js";

export interface IpcDispatcherDeps {
  // The token generated by the wrapper at startup and passed to the child
  // via the NEXTLY_IPC_TOKEN env var. All /__nextly/* requests must carry
  // this token in the x-nextly-ipc-token header.
  token: string;
  // Callbacks fired when the wrapper signals state changes. The caller wires
  // these to schema-version bumping and banner state.
  onPending: (payload: PendingChangePayload) => void;
  onApplied: (payload: AppliedChangePayload) => void;
}

export interface IpcDispatcher {
  // Handle an HTTP request. Returns null if the path is not an IPC path so
  // the caller can fall through to normal routing.
  handle(req: Request): Promise<Response | null>;

  // Queue an apply request from the admin UI apply endpoint. The wrapper
  // polls GET /apply-request to receive these.
  pushApplyRequest(
    input: Omit<ApplyRequest, "id" | "confirmed">
  ): Promise<ApplyRequestResult>;
}

export function createIpcDispatcher(deps: IpcDispatcherDeps): IpcDispatcher {
  // Apply requests waiting for the wrapper to pick them up. Drained on GET.
  const applyRequestQueue: ApplyRequest[] = [];

  // Pending apply promises keyed by request id so pushApplyRequest can await
  // the wrapper's POST /apply-result and hand the result back to the admin
  // endpoint caller.
  const pendingApplies = new Map<
    string,
    (result: ApplyRequestResult) => void
  >();

  function checkAuth(req: Request): Response | null {
    const provided = req.headers.get("x-nextly-ipc-token");
    if (!validateIpcToken(provided, deps.token)) {
      return new Response("unauthorized", { status: 401 });
    }
    return null;
  }

  async function handle(req: Request): Promise<Response | null> {
    const url = new URL(req.url);
    if (!url.pathname.startsWith("/__nextly/")) return null;

    const denied = checkAuth(req);
    if (denied) return denied;

    switch (url.pathname) {
      case "/__nextly/health":
        return new Response("ok", { status: 200 });

      case "/__nextly/pending": {
        if (req.method !== "POST") {
          return new Response("method not allowed", { status: 405 });
        }
        const payload = (await req.json()) as PendingChangePayload;
        deps.onPending(payload);
        return new Response(null, { status: 204 });
      }

      case "/__nextly/applied": {
        if (req.method !== "POST") {
          return new Response("method not allowed", { status: 405 });
        }
        const payload = (await req.json()) as AppliedChangePayload;
        deps.onApplied(payload);
        return new Response(null, { status: 204 });
      }

      case "/__nextly/apply-request": {
        if (req.method !== "GET") {
          return new Response("method not allowed", { status: 405 });
        }
        // Drain queue so the wrapper doesn't see the same requests twice.
        const drained = applyRequestQueue.splice(0);
        return new Response(JSON.stringify(drained), {
          status: 200,
          headers: { "content-type": "application/json" },
        });
      }

      case "/__nextly/apply-result": {
        if (req.method !== "POST") {
          return new Response("method not allowed", { status: 405 });
        }
        const result = (await req.json()) as ApplyRequestResult;
        const resolver = pendingApplies.get(result.id);
        if (resolver) {
          pendingApplies.delete(result.id);
          resolver(result);
        }
        return new Response(null, { status: 204 });
      }

      default:
        return new Response("not found", { status: 404 });
    }
  }

  function pushApplyRequest(
    input: Omit<ApplyRequest, "id" | "confirmed">
  ): Promise<ApplyRequestResult> {
    const id = randomUUID();
    const request: ApplyRequest = { id, ...input, confirmed: true };
    applyRequestQueue.push(request);
    return new Promise(resolve => {
      pendingApplies.set(id, resolve);
    });
  }

  return { handle, pushApplyRequest };
}
