/**
 * Canonical NextlyError codes and their HTTP status mappings.
 *
 * Plugin codes outside this enum must always pass an explicit `statusCode`
 * to the NextlyError constructor (no enum lookup happens for unknown codes).
 */
export const NEXTLY_ERROR_STATUS = {
  VALIDATION_ERROR: 400,
  INVALID_INPUT: 400,
  AUTH_REQUIRED: 401,
  AUTH_INVALID_CREDENTIALS: 401,
  TOKEN_EXPIRED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  DUPLICATE: 409,
  RATE_LIMITED: 429,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,
  INTERNAL_ERROR: 500,
  DATABASE_ERROR: 500,
  EXTERNAL_SERVICE_ERROR: 502,
  SERVICE_UNAVAILABLE: 503,
  FILENAME_INVALID: 400,
  EXTENSION_BLOCKED: 400,
  MIME_BLOCKED: 415,
  MIME_NOT_ALLOWED: 415,
  SIZE_EXCEEDED: 413,
  MAGIC_BYTE_MISMATCH: 400,
  SVG_SANITIZATION_FAILED: 400,
  UNSUPPORTED_FOR_BACKEND: 415,
  // Plan B — schema bookkeeping consolidation.
  NEXTLY_LEGACY_BOOKKEEPING_DETECTED: 409,
  NEXTLY_UPGRADE_TABLE_NAME_COLLISION: 409,
  NEXTLY_UPGRADE_IN_PROGRESS: 409,
  // Plan C2 — nextly migrate phases.
  NEXTLY_MIGRATE_LOCK_BUSY: 409,
  NEXTLY_CORE_DESTRUCTIVE_REFUSED: 409,
  NEXTLY_MIGRATION_DRIFT: 409,
  NEXTLY_MIGRATION_APPLY_FAILED: 500,
} as const;

export type NextlyErrorCode = keyof typeof NEXTLY_ERROR_STATUS;
