// Regenerates AGENTS.measured.md from live measurements, so AGENTS.md can hold
// rules while the numbers those rules cite stay fresh. A quoted figure in a
// hand-written document is stale the day after it is written; a generated file
// carries its own measurement date and the exact command, so a reader can
// re-run rather than trust.
//
// Cheap facts run on every invocation. Facts needing a forced, cache-cold
// turbo run are heavy (minutes of CPU) and run only with --full; without it
// they are listed as not measured in this run, never seeded from memory —
// an unmeasured row must not look like a measured one.
//
//   node scripts/measure-facts.mjs           # cheap facts only
//   node scripts/measure-facts.mjs --full    # also the forced turbo runs

import { execSync } from "node:child_process";
import { writeFileSync, readFileSync, readdirSync } from "node:fs";

const FULL = process.argv.includes("--full");

// Each fact returns a short string; a thrown error records the failure text
// instead, so a broken measurement is visible rather than absent.
function sh(cmd, opts = {}) {
  return execSync(cmd, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], ...opts }).trim();
}

// The turbo summary line ("Tasks: N successful, M total") is the number the
// humans quote, so it is the number recorded.
function turboSummary(cmd) {
  let out = "";
  try {
    out = sh(cmd, { maxBuffer: 64 * 1024 * 1024 });
  } catch (e) {
    out = `${e.stdout || ""}${e.stderr || ""}`;
  }
  const m = out.match(/Tasks:\s+(\d+)\s+successful,\s+(\d+)\s+total/);
  return m ? `${m[1]} of ${m[2]} successful` : "summary line not found (turbo output format changed?)";
}

const facts = [
  {
    id: "packages",
    what: "packages in the workspace",
    cmd: "ls packages | wc -l",
    run: () => `${readdirSync("packages").length}: ${readdirSync("packages").join(", ")}`,
  },
  {
    id: "pr-scopes",
    what: "PR scopes accepted by the title check (the enforced list; commitlint checks format only, not scope membership)",
    cmd: "sed -n '/scopes: |/,/requireScope/p' .github/workflows/pr-title.yml",
    run: () => {
      const y = readFileSync(".github/workflows/pr-title.yml", "utf8");
      const m = y.match(/scopes: \|\n([\s\S]*?)\n\s+requireScope/);
      return m ? m[1].split("\n").map(l => l.trim()).filter(Boolean).join(", ") : "scopes block not found";
    },
  },
  {
    id: "engines",
    what: "supported node ranges and the pinned pnpm",
    cmd: "node -e \"const p=require('./package.json');console.log(p.engines.node, p.packageManager)\"",
    run: () => {
      const p = JSON.parse(readFileSync("package.json", "utf8"));
      return `node ${p.engines.node} · ${p.packageManager}`;
    },
  },
  {
    id: "comment-convention",
    what: "comment-convention baseline (allowlisted pre-existing offences)",
    cmd: "node scripts/check-comment-convention.mjs | tail -1",
    run: () => sh("node scripts/check-comment-convention.mjs 2>&1 | tail -1", { maxBuffer: 16 * 1024 * 1024 }),
  },
  {
    id: "check-types-cold",
    what: "check-types on a clean tree, cache forced off (the honest failure count before a build)",
    cmd: "pnpm turbo run check-types --continue --force",
    heavy: true,
    run: () => turboSummary("pnpm turbo run check-types --continue --force"),
  },
  {
    id: "lint-cold",
    what: "lint on a clean tree, cache forced off",
    cmd: "pnpm turbo run lint --continue --force",
    heavy: true,
    run: () => turboSummary("pnpm turbo run lint --continue --force"),
  },
];

const lines = [
  "<!-- GENERATED by scripts/measure-facts.mjs — do not edit. -->",
  `<!-- Regenerate: node scripts/measure-facts.mjs${FULL ? " --full" : ""} · run at ${new Date().toISOString()} -->`,
  "",
  "# Measured facts",
  "",
  "Perishable numbers referenced by AGENTS.md. Every row names its command so",
  "a doubtful reader re-runs it instead of trusting the file. Heavy rows need",
  "`--full` and a tree whose cache state you know — a warm cache overstates",
  "health and a missing `dist` overstates breakage.",
  "",
];

for (const f of facts) {
  lines.push(`## ${f.id}`, "", f.what, "", "```", `$ ${f.cmd}`);
  if (f.heavy && !FULL) {
    lines.push("(not measured in this run — heavy; re-run with --full)");
  } else {
    let v;
    try { v = f.run(); } catch (e) { v = `MEASUREMENT FAILED: ${String(e.message).split("\n")[0]}`; }
    lines.push(v);
  }
  lines.push("```", "");
}

writeFileSync("AGENTS.measured.md", lines.join("\n"));
process.stdout.write(`AGENTS.measured.md written (${FULL ? "full" : "cheap"} run)\n`);
