// Regenerates AGENTS.measured.md from live measurements, so AGENTS.md can hold
// rules while the numbers those rules cite stay fresh. A quoted figure in a
// hand-written document is stale the day after it is written; a generated file
// carries its own measurement date and the exact command, so a reader can
// re-run rather than trust.
//
// Cheap facts run on every invocation. Facts needing a forced turbo run are
// heavy (minutes of CPU) and run only with --full; without it they are listed
// as not measured in this run, never seeded from memory — an unmeasured row
// must not look like a measured one.
//
// Two properties this file holds deliberately:
// - the command shown in each row is the command that RAN — one
//   implementation of each question, so display and measurement cannot drift;
// - a command's exit status is captured beside its output, never lost to a
//   pipeline, so a failing measurement reads as a failure rather than as a
//   number.
//
//   node scripts/measure-facts.mjs           # cheap facts only
//   node scripts/measure-facts.mjs --full    # also the forced turbo runs

import { spawnSync } from "node:child_process";
import { writeFileSync, existsSync, readdirSync } from "node:fs";

const FULL = process.argv.includes("--full");

// Runs the row's own command and reports output AND status together. spawnSync
// through bash keeps shell syntax available without a pipeline swallowing the
// exit code: the status here is the whole command's, read directly.
function measure(cmd) {
  const r = spawnSync("bash", ["-o", "pipefail", "-c", cmd], {
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  const out = `${r.stdout || ""}${r.stderr || ""}`.trim();
  return { out, status: r.status };
}

// The turbo summary line ("Tasks: N successful, M total") is the number the
// humans quote, so it is the number recorded — with the run's exit status,
// because turbo exits nonzero when tasks fail and that is part of the reading.
function turboRow(cmd) {
  const { out, status } = measure(cmd);
  const m = out.match(/Tasks:\s+(\d+)\s+successful,\s+(\d+)\s+total/);
  return {
    out: m ? `${m[1]} of ${m[2]} successful` : "summary line not found (turbo output format changed?)",
    status,
  };
}

// Heavy rows depend on what is already built: a forced run reads no cache, but
// an existing dist still satisfies the sibling imports the cold numbers are
// about. Recording the dist-state beside the number lets a reader interpret it
// instead of trusting a label the generator never established.
function distState() {
  const pkgs = readdirSync("packages").filter(p => existsSync(`packages/${p}/package.json`));
  const built = pkgs.filter(p => existsSync(`packages/${p}/dist`));
  return `${built.length} of ${pkgs.length} packages have dist/`;
}

const facts = [
  {
    id: "packages",
    what: "packages in the workspace",
    cmd: "ls packages | tr '\\n' ' '",
  },
  {
    id: "pr-scopes",
    what: "PR scopes accepted by the title check (the enforced list; commitlint checks format only, not scope membership)",
    cmd: "sed -n '/scopes: |/,/requireScope/p' .github/workflows/pr-title.yml | sed '1d;$d' | tr -d ' ' | tr '\\n' ' '",
  },
  {
    id: "engines",
    what: "supported node ranges and the pinned pnpm",
    cmd: `node -e "const p=require('./package.json');console.log(p.engines.node, '·', p.packageManager)"`,
  },
  {
    id: "comment-convention",
    what: "comment-convention baseline (allowlisted pre-existing offences)",
    cmd: "node scripts/check-comment-convention.mjs 2>&1 | tail -1",
  },
  {
    id: "check-types-cold",
    what: "check-types with the turbo cache forced off (read the dist-state line before interpreting)",
    cmd: "pnpm turbo run check-types --continue --force",
    heavy: true,
  },
  {
    id: "lint-cold",
    what: "lint with the turbo cache forced off (read the dist-state line before interpreting)",
    cmd: "pnpm turbo run lint --continue --force",
    heavy: true,
  },
];

const lines = [
  "<!-- GENERATED by scripts/measure-facts.mjs — do not edit. -->",
  `<!-- Regenerate: node scripts/measure-facts.mjs${FULL ? " --full" : ""} · run at ${new Date().toISOString()} -->`,
  "",
  "# Measured facts",
  "",
  "Perishable numbers referenced by AGENTS.md. Every row shows the command that",
  "actually ran and its exit status, so a doubtful reader re-runs instead of",
  "trusting and a failed measurement cannot read as a number. Heavy rows need",
  "`--full`; their meaning depends on the build state recorded beside them.",
  "",
];

for (const f of facts) {
  lines.push(`## ${f.id}`, "", f.what, "", "```", `$ ${f.cmd}`);
  if (f.heavy && !FULL) {
    lines.push("(not measured in this run — heavy; re-run with --full)");
  } else if (f.heavy) {
    const { out, status } = turboRow(f.cmd);
    lines.push(`${out}  [exit ${status}]`, `dist-state at measurement: ${distState()}`);
  } else {
    const { out, status } = measure(f.cmd);
    lines.push(status === 0 ? out : `MEASUREMENT FAILED [exit ${status}]: ${out.split("\n").slice(-1)[0]}`);
  }
  lines.push("```", "");
}

writeFileSync("AGENTS.measured.md", lines.join("\n"));
process.stdout.write(`AGENTS.measured.md written (${FULL ? "full" : "cheap"} run)\n`);
