/**
 * Generated by `nextly migrate:create --plugin`. Edit the plugin's
 * schema and regenerate — a hand edit fails the module's own checksum.
 */
import type { PluginMigration } from "@nextlyhq/plugin-sdk/schema";

export default {
  name: "20260929_054719_794_create_notes",
  schemaVersion: 1,
  checksum: "9ed7907491982a86ad70ccbfbc36e2f20d48b0b6ed7cbe21377f1ead65c6d468",
  dialects: {
    postgresql: {
      up: [
        'CREATE TABLE "fx__notes" (\n  "id" text PRIMARY KEY NOT NULL,\n  "author_id" varchar(255) NOT NULL,\n  "title" varchar(255) NOT NULL,\n  "body" text,\n  "rank" int4 NOT NULL DEFAULT 0,\n  "score" numeric(10, 2),\n  "metadata" jsonb,\n  "created_at" timestamp NOT NULL DEFAULT now(),\n  "updated_at" timestamp NOT NULL DEFAULT now()\n);\nCREATE UNIQUE INDEX IF NOT EXISTS "uq_fx__notes_author_id_title_0i6s4c4" ON "fx__notes" ("author_id", "title")',
        'CREATE TABLE "fx__tags" (\n  "id" text PRIMARY KEY NOT NULL,\n  "label" text NOT NULL,\n  "created_at" timestamp NOT NULL DEFAULT now(),\n  "updated_at" timestamp NOT NULL DEFAULT now()\n);\nCREATE UNIQUE INDEX IF NOT EXISTS "uq_fx__tags_label" ON "fx__tags" ("label")',
      ],
      down: ['DROP TABLE "fx__tags" CASCADE', 'DROP TABLE "fx__notes" CASCADE'],
    },
    mysql: {
      up: [
        "CREATE TABLE `fx__notes` (\n  `id` varchar(36) PRIMARY KEY NOT NULL,\n  `author_id` varchar(255) NOT NULL,\n  `title` varchar(255) NOT NULL,\n  `body` text,\n  `rank` int NOT NULL DEFAULT 0,\n  `score` decimal(10,2),\n  `metadata` json,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n);\nCREATE UNIQUE INDEX `uq_fx__notes_author_id_title_0i6s4c4` ON `fx__notes` (`author_id`, `title`)",
        "CREATE TABLE `fx__tags` (\n  `id` varchar(36) PRIMARY KEY NOT NULL,\n  `label` varchar(64) NOT NULL,\n  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP\n);\nCREATE UNIQUE INDEX `uq_fx__tags_label` ON `fx__tags` (`label`)",
      ],
      down: ["DROP TABLE `fx__tags`", "DROP TABLE `fx__notes`"],
    },
    sqlite: {
      up: [
        'CREATE TABLE "fx__notes" (\n  "id" text PRIMARY KEY NOT NULL,\n  "author_id" text NOT NULL,\n  "title" text NOT NULL,\n  "body" text,\n  "rank" integer NOT NULL DEFAULT 0,\n  "score" numeric,\n  "metadata" text,\n  "created_at" integer NOT NULL DEFAULT (strftime(\'%s\', \'now\')),\n  "updated_at" integer NOT NULL DEFAULT (strftime(\'%s\', \'now\'))\n);\nCREATE UNIQUE INDEX IF NOT EXISTS "uq_fx__notes_author_id_title_0i6s4c4" ON "fx__notes" ("author_id", "title")',
        'CREATE TABLE "fx__tags" (\n  "id" text PRIMARY KEY NOT NULL,\n  "label" text NOT NULL,\n  "created_at" integer NOT NULL DEFAULT (strftime(\'%s\', \'now\')),\n  "updated_at" integer NOT NULL DEFAULT (strftime(\'%s\', \'now\'))\n);\nCREATE UNIQUE INDEX IF NOT EXISTS "uq_fx__tags_label" ON "fx__tags" ("label")',
      ],
      down: ['DROP TABLE "fx__tags"', 'DROP TABLE "fx__notes"'],
    },
  },
  snapshot: {
    postgresql: {
      tables: [
        {
          name: "fx__notes",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "author_id",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "title",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "body",
              type: "text",
              nullable: true,
            },
            {
              name: "rank",
              type: "int4",
              nullable: false,
              default: "0",
            },
            {
              name: "score",
              type: "numeric(10, 2)",
              nullable: true,
            },
            {
              name: "metadata",
              type: "jsonb",
              nullable: true,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
          ],
          indexes: [
            {
              name: "uq_fx__notes_author_id_title_0i6s4c4",
              columns: ["author_id", "title"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
        {
          name: "fx__tags",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "label",
              type: "text",
              nullable: false,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
          ],
          indexes: [
            {
              name: "uq_fx__tags_label",
              columns: ["label"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
      ],
    },
    mysql: {
      tables: [
        {
          name: "fx__notes",
          columns: [
            {
              name: "id",
              type: "varchar(36)",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "author_id",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "title",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "body",
              type: "text",
              nullable: true,
            },
            {
              name: "rank",
              type: "int",
              nullable: false,
              default: "0",
            },
            {
              name: "score",
              type: "decimal(10,2)",
              nullable: true,
            },
            {
              name: "metadata",
              type: "json",
              nullable: true,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
          ],
          indexes: [
            {
              name: "uq_fx__notes_author_id_title_0i6s4c4",
              columns: ["author_id", "title"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
        {
          name: "fx__tags",
          columns: [
            {
              name: "id",
              type: "varchar(36)",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "label",
              type: "varchar(64)",
              nullable: false,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
          ],
          indexes: [
            {
              name: "uq_fx__tags_label",
              columns: ["label"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
      ],
    },
    sqlite: {
      tables: [
        {
          name: "fx__notes",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "author_id",
              type: "text",
              nullable: false,
            },
            {
              name: "title",
              type: "text",
              nullable: false,
            },
            {
              name: "body",
              type: "text",
              nullable: true,
            },
            {
              name: "rank",
              type: "integer",
              nullable: false,
              default: "0",
            },
            {
              name: "score",
              type: "numeric",
              nullable: true,
            },
            {
              name: "metadata",
              type: "text",
              nullable: true,
            },
            {
              name: "created_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
            {
              name: "updated_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
          ],
          indexes: [
            {
              name: "uq_fx__notes_author_id_title_0i6s4c4",
              columns: ["author_id", "title"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
        {
          name: "fx__tags",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "label",
              type: "text",
              nullable: false,
            },
            {
              name: "created_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
            {
              name: "updated_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
          ],
          indexes: [
            {
              name: "uq_fx__tags_label",
              columns: ["label"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
      ],
    },
  },
  before: {
    postgresql: {
      tables: [],
    },
    mysql: {
      tables: [],
    },
    sqlite: {
      tables: [],
    },
  },
  contributed: {
    postgresql: {
      tables: [],
    },
    mysql: {
      tables: [],
    },
    sqlite: {
      tables: [],
    },
  },
  contributedBefore: {
    postgresql: {
      tables: [],
    },
    mysql: {
      tables: [],
    },
    sqlite: {
      tables: [],
    },
  },
} satisfies PluginMigration;
