/**
 * Generated by `nextly migrate:create --plugin`. Edit the plugin's
 * schema and regenerate — a hand edit fails the module's own checksum.
 */
import type { PluginMigration } from "@nextlyhq/plugin-sdk/schema";

export default {
  name: "20260929_054736_388_add_pinned",
  schemaVersion: 2,
  checksum: "4191f0fb7025ecffacdfaf6a4c51ffea3d6d7dce5e1d1be3dd1e2b20b9aa62c9",
  dialects: {
    postgresql: {
      up: [
        'ALTER TABLE "fx__notes" ADD COLUMN "pinned" bool NOT NULL DEFAULT false',
        'CREATE INDEX IF NOT EXISTS "idx_fx__notes_pinned" ON "fx__notes" ("pinned")',
      ],
      down: [
        'DROP INDEX IF EXISTS "idx_fx__notes_pinned"',
        'ALTER TABLE "fx__notes" DROP COLUMN "pinned"',
      ],
    },
    mysql: {
      up: [
        "ALTER TABLE `fx__notes` ADD COLUMN `pinned` tinyint(1) NOT NULL DEFAULT false",
        "CREATE INDEX `idx_fx__notes_pinned` ON `fx__notes` (`pinned`)",
      ],
      down: [
        "DROP INDEX `idx_fx__notes_pinned` ON `fx__notes`",
        "ALTER TABLE `fx__notes` DROP COLUMN `pinned`",
      ],
    },
    sqlite: {
      up: [
        'ALTER TABLE "fx__notes" ADD COLUMN "pinned" integer NOT NULL DEFAULT false',
        'CREATE INDEX IF NOT EXISTS "idx_fx__notes_pinned" ON "fx__notes" ("pinned")',
      ],
      down: [
        'DROP INDEX IF EXISTS "idx_fx__notes_pinned"',
        'ALTER TABLE "fx__notes" DROP COLUMN "pinned"',
      ],
    },
  },
  snapshot: {
    postgresql: {
      tables: [
        {
          name: "fx__notes",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "author_id",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "title",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "body",
              type: "text",
              nullable: true,
            },
            {
              name: "pinned",
              type: "bool",
              nullable: false,
              default: "false",
            },
            {
              name: "rank",
              type: "int4",
              nullable: false,
              default: "0",
            },
            {
              name: "score",
              type: "numeric(10, 2)",
              nullable: true,
            },
            {
              name: "metadata",
              type: "jsonb",
              nullable: true,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
          ],
          indexes: [
            {
              name: "uq_fx__notes_author_id_title_0i6s4c4",
              columns: ["author_id", "title"],
              unique: true,
            },
            {
              name: "idx_fx__notes_pinned",
              columns: ["pinned"],
              unique: false,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
        {
          name: "fx__tags",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "label",
              type: "text",
              nullable: false,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
          ],
          indexes: [
            {
              name: "uq_fx__tags_label",
              columns: ["label"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
      ],
    },
    mysql: {
      tables: [
        {
          name: "fx__notes",
          columns: [
            {
              name: "id",
              type: "varchar(36)",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "author_id",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "title",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "body",
              type: "text",
              nullable: true,
            },
            {
              name: "pinned",
              type: "tinyint(1)",
              nullable: false,
              default: "false",
            },
            {
              name: "rank",
              type: "int",
              nullable: false,
              default: "0",
            },
            {
              name: "score",
              type: "decimal(10,2)",
              nullable: true,
            },
            {
              name: "metadata",
              type: "json",
              nullable: true,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
          ],
          indexes: [
            {
              name: "uq_fx__notes_author_id_title_0i6s4c4",
              columns: ["author_id", "title"],
              unique: true,
            },
            {
              name: "idx_fx__notes_pinned",
              columns: ["pinned"],
              unique: false,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
        {
          name: "fx__tags",
          columns: [
            {
              name: "id",
              type: "varchar(36)",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "label",
              type: "varchar(64)",
              nullable: false,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
          ],
          indexes: [
            {
              name: "uq_fx__tags_label",
              columns: ["label"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
      ],
    },
    sqlite: {
      tables: [
        {
          name: "fx__notes",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "author_id",
              type: "text",
              nullable: false,
            },
            {
              name: "title",
              type: "text",
              nullable: false,
            },
            {
              name: "body",
              type: "text",
              nullable: true,
            },
            {
              name: "pinned",
              type: "integer",
              nullable: false,
              default: "false",
            },
            {
              name: "rank",
              type: "integer",
              nullable: false,
              default: "0",
            },
            {
              name: "score",
              type: "numeric",
              nullable: true,
            },
            {
              name: "metadata",
              type: "text",
              nullable: true,
            },
            {
              name: "created_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
            {
              name: "updated_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
          ],
          indexes: [
            {
              name: "uq_fx__notes_author_id_title_0i6s4c4",
              columns: ["author_id", "title"],
              unique: true,
            },
            {
              name: "idx_fx__notes_pinned",
              columns: ["pinned"],
              unique: false,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
        {
          name: "fx__tags",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "label",
              type: "text",
              nullable: false,
            },
            {
              name: "created_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
            {
              name: "updated_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
          ],
          indexes: [
            {
              name: "uq_fx__tags_label",
              columns: ["label"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
      ],
    },
  },
  before: {
    postgresql: {
      tables: [
        {
          name: "fx__notes",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "author_id",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "title",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "body",
              type: "text",
              nullable: true,
            },
            {
              name: "rank",
              type: "int4",
              nullable: false,
              default: "0",
            },
            {
              name: "score",
              type: "numeric(10, 2)",
              nullable: true,
            },
            {
              name: "metadata",
              type: "jsonb",
              nullable: true,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
          ],
          indexes: [
            {
              name: "uq_fx__notes_author_id_title_0i6s4c4",
              columns: ["author_id", "title"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
        {
          name: "fx__tags",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "label",
              type: "text",
              nullable: false,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "now()",
            },
          ],
          indexes: [
            {
              name: "uq_fx__tags_label",
              columns: ["label"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
      ],
    },
    mysql: {
      tables: [
        {
          name: "fx__notes",
          columns: [
            {
              name: "id",
              type: "varchar(36)",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "author_id",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "title",
              type: "varchar(255)",
              nullable: false,
            },
            {
              name: "body",
              type: "text",
              nullable: true,
            },
            {
              name: "rank",
              type: "int",
              nullable: false,
              default: "0",
            },
            {
              name: "score",
              type: "decimal(10,2)",
              nullable: true,
            },
            {
              name: "metadata",
              type: "json",
              nullable: true,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
          ],
          indexes: [
            {
              name: "uq_fx__notes_author_id_title_0i6s4c4",
              columns: ["author_id", "title"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
        {
          name: "fx__tags",
          columns: [
            {
              name: "id",
              type: "varchar(36)",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "label",
              type: "varchar(64)",
              nullable: false,
            },
            {
              name: "created_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
            {
              name: "updated_at",
              type: "timestamp",
              nullable: false,
              default: "CURRENT_TIMESTAMP",
            },
          ],
          indexes: [
            {
              name: "uq_fx__tags_label",
              columns: ["label"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
      ],
    },
    sqlite: {
      tables: [
        {
          name: "fx__notes",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "author_id",
              type: "text",
              nullable: false,
            },
            {
              name: "title",
              type: "text",
              nullable: false,
            },
            {
              name: "body",
              type: "text",
              nullable: true,
            },
            {
              name: "rank",
              type: "integer",
              nullable: false,
              default: "0",
            },
            {
              name: "score",
              type: "numeric",
              nullable: true,
            },
            {
              name: "metadata",
              type: "text",
              nullable: true,
            },
            {
              name: "created_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
            {
              name: "updated_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
          ],
          indexes: [
            {
              name: "uq_fx__notes_author_id_title_0i6s4c4",
              columns: ["author_id", "title"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
        {
          name: "fx__tags",
          columns: [
            {
              name: "id",
              type: "text",
              nullable: false,
              primaryKey: true,
            },
            {
              name: "label",
              type: "text",
              nullable: false,
            },
            {
              name: "created_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
            {
              name: "updated_at",
              type: "integer",
              nullable: false,
              default: "(strftime('%s', 'now'))",
            },
          ],
          indexes: [
            {
              name: "uq_fx__tags_label",
              columns: ["label"],
              unique: true,
            },
          ],
          foreignKeys: [],
          checks: [],
        },
      ],
    },
  },
  contributed: {
    postgresql: {
      tables: [],
    },
    mysql: {
      tables: [],
    },
    sqlite: {
      tables: [],
    },
  },
  contributedBefore: {
    postgresql: {
      tables: [],
    },
    mysql: {
      tables: [],
    },
    sqlite: {
      tables: [],
    },
  },
} satisfies PluginMigration;
