/**
 * Generated by `nextly migrate:create --plugin`. Rewritten on every
 * generation; the runner sorts by module name anyway, so a hand reorder
 * changes nothing.
 */
import m20260929_054719_794_create_notes from "./20260929_054719_794_create_notes";
import m20260929_054736_388_add_pinned from "./20260929_054736_388_add_pinned";

export const migrations = [
  m20260929_054719_794_create_notes,
  m20260929_054736_388_add_pinned,
];
