/**
 * Nextly Initialization — Service Config Builder
 *
 * Merges caller-provided configuration with the loaded `nextly.config.ts`
 * into a final `NextlyServiceConfig` passed to the DI container.
 *
 * Extracted from `init.ts` so initialization orchestration can stay
 * focused on cache/lifecycle concerns.
 *
 * @module init/build-service-config
 */

import type { SanitizedNextlyConfig } from "../collections/config/define-config";
import type { NextlyServiceConfig } from "../di/register";
import { assertNoLegacyFieldGroupKey } from "../shared/legacy-field-group-key";
import { getImageProcessor } from "../storage/image-processor";

/**
 * Configuration options for getNextly().
 *
 * Extends NextlyServiceConfig with a REQUIRED `config` property carrying the
 * loaded `nextly.config.ts`. It mirrors Payload's `getPayload({ config })`
 * contract: passing config on every call eliminates a class of "I forgot the
 * wrapper" bugs where a stray import bypassed the project-local wrapper and silently
 * bootstrapped an empty collections registry.
 *
 * Internal handlers that just need the cached singleton (post-init) should
 * call `getCachedNextly()` instead.
 */
export interface GetNextlyOptions extends Partial<NextlyServiceConfig> {
  /**
   * Pre-loaded Nextly configuration from nextly.config.ts. Required.
   *
   * The recommended import is via the `@nextly-config` TypeScript path
   * alias auto-generated by `create-nextly-app`:
   *
   * @example
   * ```typescript
   * import { getNextly } from 'nextly';
   * import config from '@nextly-config';
   *
   * const nextly = await getNextly({ config });
   * ```
   */
  config: SanitizedNextlyConfig;
}

/**
 * Build the final service configuration.
 *
 * Priority:
 * 1. Explicitly provided storagePlugins take precedence
 * 2. Storage plugins from provided config (nextly.config.ts) are used if available
 * 3. Collections from nextly.config.ts are forwarded if not explicitly provided
 * 4. Plugins from nextly.config.ts are forwarded if not explicitly provided
 * 5. Default image processor is used if not provided
 *
 * @param providedConfig - Config options provided by the user
 * @returns Complete service configuration
 */

export function buildServiceConfig(
  providedConfig?: GetNextlyOptions
): NextlyServiceConfig {
  // Start with provided config or empty object
  const serviceConfig: Partial<NextlyServiceConfig> = {};

  // Copy over service config properties (excluding 'config')
  if (providedConfig) {
    const { config: nextlyConfig, ...rest } = providedConfig;
    Object.assign(serviceConfig, rest);

    // AFTER the caller spread, and derived only from the nested config, so a
    // caller cannot set it directly. It is internal wiring, not an option: the
    // gate it opens must match what `runProdMigrationsIfEnabled` will actually
    // do, and that reads `config.db.runMigrationsOnBoot`. A caller passing a
    // conflicting top-level value would open no gate while migrations ran
    // anyway — the exact unguarded window this exists to close.
    serviceConfig.runMigrationsOnBoot =
      nextlyConfig?.db?.runMigrationsOnBoot === true;

    // Forwarded from the nested config for the same reason as the fields below:
    // the nested object is destructured away here, so anything not named again
    // never reaches the container. The minting endpoint reads this to learn
    // where the preview route is mounted, and an absent value means every
    // non-default mount silently hands out links to `/api/preview`.
    if (serviceConfig.preview === undefined && nextlyConfig?.preview) {
      serviceConfig.preview = nextlyConfig.preview;
    }

    // If storagePlugins not explicitly provided, use from nextly.config.ts
    if (!serviceConfig.storagePlugins && nextlyConfig?.storage) {
      serviceConfig.storagePlugins = nextlyConfig.storage;
      if (nextlyConfig.storage.length > 0) {
        console.log(
          `[Nextly] Using ${nextlyConfig.storage.length} storage plugin(s) from config`
        );
      }
    }

    // If collections not explicitly provided, use from nextly.config.ts
    if (!serviceConfig.collections && nextlyConfig?.collections) {
      serviceConfig.collections = nextlyConfig.collections;
      if (nextlyConfig.collections.length > 0) {
        console.log(
          `[Nextly] Using ${nextlyConfig.collections.length} collection(s) from config`
        );
      }
    }

    // Validated before flattening: the nested config is destructured away
    // here, so a legacy key on it would never reach the boot-time guard.
    assertNoLegacyFieldGroupKey(nextlyConfig, "buildServiceConfig");

    // If singles not explicitly provided, use from nextly.config.ts
    if (!serviceConfig.singles && nextlyConfig?.singles) {
      serviceConfig.singles = nextlyConfig.singles;
      if (nextlyConfig.singles.length > 0) {
        console.log(
          `[Nextly] Using ${nextlyConfig.singles.length} single(s) from config`
        );
      }
    }

    // If field groups not explicitly provided, use from nextly.config.ts
    if (!serviceConfig.fieldGroups && nextlyConfig?.fieldGroups) {
      serviceConfig.fieldGroups = nextlyConfig.fieldGroups;
      if (nextlyConfig.fieldGroups.length > 0) {
        console.log(
          `[Nextly] Using ${nextlyConfig.fieldGroups.length} field group(s) from config`
        );
      }
    }

    // App-declared job types, forwarded like plugins. Without this the field is
    // accepted by the public config and never reaches the collector that
    // registers it — an option that validates and does nothing.
    if (!serviceConfig.jobs && nextlyConfig?.jobs) {
      serviceConfig.jobs = nextlyConfig.jobs;
    }

    // If plugins not explicitly provided, use from nextly.config.ts
    if (!serviceConfig.plugins && nextlyConfig?.plugins) {
      serviceConfig.plugins = nextlyConfig.plugins;
      if (nextlyConfig.plugins.length > 0) {
        console.log(
          `[Nextly] Using ${nextlyConfig.plugins.length} plugin(s) from config`
        );
      }
    }

    // If app-level custom permissions not explicitly provided, use from
    // nextly.config.ts so they seed alongside plugin permissions (D36).
    if (!serviceConfig.permissions && nextlyConfig?.permissions) {
      serviceConfig.permissions = nextlyConfig.permissions;
    }

    // If users config not explicitly provided, use from nextly.config.ts
    if (!serviceConfig.users && nextlyConfig?.users) {
      serviceConfig.users = nextlyConfig.users;
    }

    // If email config not explicitly provided, use from nextly.config.ts
    if (!serviceConfig.email && nextlyConfig?.email) {
      serviceConfig.email = nextlyConfig.email;
    }

    // If apiKeys config not explicitly provided, use from nextly.config.ts
    if (!serviceConfig.apiKeys && nextlyConfig?.apiKeys) {
      serviceConfig.apiKeys = nextlyConfig.apiKeys;
    }

    // Same for rate limiting. Carried for `store` above all: it is the only
    // route by which a deployment can give the AUTH limiter a shared window,
    // and dropping it here would leave the credential paths per-process no
    // matter what the config said.
    if (!serviceConfig.rateLimit && nextlyConfig?.rateLimit) {
      serviceConfig.rateLimit = nextlyConfig.rateLimit;
    }

    // If security config not explicitly provided, use from nextly.config.ts
    if (!serviceConfig.security && nextlyConfig?.security) {
      serviceConfig.security = nextlyConfig.security;
    }

    // Admin config (branding, plugin overrides, devAutoLogin) - carry
    // through so DI consumers can read admin-level toggles.
    if (!serviceConfig.admin && nextlyConfig?.admin) {
      serviceConfig.admin = nextlyConfig.admin;
    }

    // Auth config (revealRegistrationConflict and friends) - carry
    // through so the auth handlers can read these flags from the DI's
    // "config" service.
    if (!serviceConfig.auth && nextlyConfig?.auth) {
      serviceConfig.auth = nextlyConfig.auth;
    }

    // Localization (i18n) - carry the normalized block through so the
    // data-layer services (CollectionQueryService / CollectionMutationService /
    // CollectionsHandler) receive it. Without this, ctx.config.localization is
    // undefined and every localized read/write silently no-ops to the main
    // table while the admin chrome still shows the switcher.
    // `nextlyConfig` is a SanitizedNextlyConfig, so this is already normalized.
    if (!serviceConfig.localization && nextlyConfig?.localization) {
      serviceConfig.localization = nextlyConfig.localization;
    }

    // Webhook retention — carry the resolved policy through so writes can offer
    // a retention pass. `undefined` here means "not carried"; the sanitizer
    // always produces either a policy or an explicit null, so a null must be
    // preserved rather than treated as absent.
    if (
      serviceConfig.webhookRetention === undefined &&
      nextlyConfig?.webhookRetention !== undefined
    ) {
      serviceConfig.webhookRetention = nextlyConfig.webhookRetention;
    }

    // Audit retention — carry the resolved windows through, for the same reason
    // as the webhook policy above: the write paths read them to decide whether
    // to register an audit pass, and an uncarried policy reads as "no retention
    // configured" rather than as the defaults the sanitizer produced.
    if (
      serviceConfig.auditRetention === undefined &&
      nextlyConfig?.auditRetention !== undefined
    ) {
      serviceConfig.auditRetention = nextlyConfig.auditRetention;
    }

    // Delivery-log retention — carried for the same reason, and with the same
    // consequence if it is not: the email registration reads it to decide
    // whether to offer a sweep, and an uncarried policy leaves the table
    // unswept while the configuration reads as enforced.
    if (
      serviceConfig.emailRetention === undefined &&
      nextlyConfig?.emailRetention !== undefined
    ) {
      serviceConfig.emailRetention = nextlyConfig.emailRetention;
    }

    // Audit seam — carry the resolved flag through so the webhook registration
    // can publish it to the recording gate. `undefined` means not carried; the
    // sanitizer always produces a boolean, so any value here is authoritative.
    if (
      serviceConfig.webhookAuditEnabled === undefined &&
      nextlyConfig?.webhookAuditEnabled !== undefined
    ) {
      serviceConfig.webhookAuditEnabled = nextlyConfig.webhookAuditEnabled;
    }
  }

  // Ensure imageProcessor is always provided
  if (!serviceConfig.imageProcessor) {
    serviceConfig.imageProcessor = getImageProcessor();
  }

  return serviceConfig as NextlyServiceConfig;
}
