/**
 * Which index scopes a backfill has already walked.
 *
 * One row per completed (collection, field, locale, variant). The row's
 * EXISTENCE is the whole record — there is no status column, because a scope is
 * recorded only after its rebuild resolved, so a row that exists is a walk that
 * finished and a scope with no row is one to do.
 *
 * ## Why a table rather than a flag
 *
 * A single "backfill done" flag is true about the site it was written for. Add
 * a collection with a blocks field, add a locale, or turn drafts on, and there
 * are scopes nothing has ever walked while the flag still says the index is
 * whole. Rows let completion be DERIVED against the scopes that exist now, so a
 * site that grows goes back to reporting a floor until the new work is done.
 *
 * It also makes the work resumable at its natural unit. A rebuild walks one
 * scope; recording one row per scope means an interrupted backfill resumes
 * where it stopped rather than starting over, which on a large site is the
 * difference between finishing and being retried for ever.
 *
 * @module collections/usage-backfill-state
 */
import { defineCollection, text } from "nextly/config";

/** The slug the backfill's progress is stored under. */
export const USAGE_BACKFILL_STATE_SLUG = "nx_pb_usage_backfill";

/** One row: this scope has been walked. */
export interface UsageBackfillStateRow {
  /**
   * Which derivation this scope was walked under.
   *
   * A row is evidence about work done with particular bounds, and the index is
   * derived under the same ones the renderer draws with. A row from a different
   * generation is not progress towards the current index, so it is read as
   * absent — see `backfillGeneration`.
   */
  generation: string;
  /**
   * The scope key, as `backfillScopeKey` composes it.
   *
   * Stored in its own column rather than used as the row id. A document id is
   * generated by core and immutable, so it cannot be chosen — which means the
   * key has to be a value this plugin can query on.
   */
  scopeKey: string;
}

/**
 * The progress collection.
 *
 * Every column is `text`, as both usage indexes are and for the same reason:
 * these are identifiers this plugin composes, not numbers, dates or
 * relationships it may assume exist.
 */
export function usageBackfillStateCollection() {
  return defineCollection({
    slug: USAGE_BACKFILL_STATE_SLUG,
    labels: { singular: "Usage backfill", plural: "Usage backfill" },
    // Bookkeeping the plugin maintains, never authored.
    internal: true,
    fields: [
      // Indexed because every pass filters on it: a pass reads the recorded
      // keys to decide what is outstanding, and that read happens on every
      // drain tick for as long as the backfill has work left. Declared on the
      // FIELD, which is the form the schema pipeline materialises — a
      // collection-level `indexes` never reaches it.
      text({ name: "scopeKey", label: "Scope key", index: true }),
      // Indexed with `scopeKey` because every pass filters on BOTH: a row only
      // counts as progress when its generation is the current one. Declared on
      // the field, which is the form the schema pipeline materialises.
      text({ name: "generation", label: "Generation", index: true }),
    ],
    access: {
      // Derived state, written only by the backfill itself. A row authored by
      // hand claims a scope was walked, and the scope it names is then never
      // revisited — so the documents in it stay unindexed while every count
      // reports itself complete. That is the one edit that can silently undo
      // the whole mechanism, which is why nothing outside may make it.
      //
      // These do NOT stop a session super-admin. The RBAC gate is ordered
      // "super-admin bypass -> code-defined access -> DB permissions", so for
      // such a caller these callbacks are never evaluated. Closing that needs a
      // write boundary external collection operations cannot cross, which is a
      // core capability rather than an access rule a plugin can declare —
      // recorded as `finding:backfill-progress-is-forgeable-by-a-super-admin`.
      // What makes it worth naming rather than shrugging at is that it does not
      // self-repair: a corrupted INDEX row is rewritten by the next sweep, and a
      // forged PROGRESS row suppresses that sweep.
      //
      // Functions returning a constant rather than bare `false`: access rules
      // are validated as callables and a boolean is rejected at config time
      // rather than read as "never". The plugin's own writes go through the
      // Direct API, which overrides access.
      create: () => false,
      update: () => false,
      delete: () => false,
      // Read is closed for the same reason the index's is: the rows enumerate
      // which collections, fields and locales exist, which is a map of the
      // site's shape to anyone who can list them.
      read: () => false,
    },
    // No webhook recording. An omitted option RECORDS — the registry reads
    // `webhooks?.record !== false` — so a site with an endpoint subscribed to
    // `entry.*` would receive an event per scope a backfill completes, which is
    // internal progress rather than anything that happened to content.
    webhooks: false,
    admin: {
      description:
        "Which parts of the component usage index have been built. Maintained automatically. Editing it changes nothing about what a page renders — but a row added here marks a scope as already walked, so its documents stay out of the index and usage counts for them read as zero.",
    },
    // A row is a fact — this scope has been walked — rather than an event, and
    // WHEN it was walked answers nothing anyone asks: a scope is redone when it
    // is missing, never because its row is old.
    timestamps: false,
  });
}
