/**
 * The plugin migration phase against a real SQLite.
 *
 * A unit test can prove the runner's ORDER and refusals with fakes, but not
 * that the SQL a module carries actually executes, introspects back equal,
 * and lands in the ledger and the owner registry. Those are properties of the
 * whole chain — DSL → draft → compile → generate → execute → introspect →
 * reconcileFile — and only a database closes it.
 *
 * The modules under test are GENERATED by the real generator from the real
 * DSL, not hand-written, so this file also covers the generate→run contract.
 * (The tampered-module and applied-then-changed refusals are additionally
 * unit-tested with fakes in run-plugin-migrations.test.ts.)
 *
 * SQLite leg runs anywhere; the Postgres/MySQL legs run in CI through the
 * same file's dialect gate.
 *
 * @module cli/commands/__tests__/migrate-plugins.integration
 */
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { describe, expect, it, beforeAll, afterAll } from "vitest";

import { buildExtensionSchema } from "../../../domains/schema/extension/build-extension-schema";
import { col, defineTable } from "../../../domains/schema/extension/dsl";
import { buildPluginMigration } from "../../../domains/schema/migrate-create/generate-plugin";
import { type PluginMigration } from "../../../domains/schema/migrate/plugin/plugin-migration";
import { reconcileCore } from "../../../domains/schema/migrate/core-reconcile";
import { CORE_TABLE_NAMES } from "../../../schemas/index";
import { createLogger } from "../../utils/logger";
import { runPluginPhase } from "../migrate";

const DIALECT = "sqlite" as const;

/** Minimal adapter surface the phase touches, backed by the live database. */
function adapterFor(sqlite: Database.Database) {
  return {
    dialect: DIALECT,
    executeQuery: async (statement: string) => {
      sqlite.exec(statement);
    },
    listTables: async () =>
      (
        sqlite
          .prepare("SELECT name FROM sqlite_master WHERE type = 'table'")
          .all() as Array<{ name: string }>
      ).map(r => r.name),
  };
}

/** The plugin's declared tables, compiled per dialect by the real builder. */
async function tablesByDialect(
  pluginName: string,
  prefix: string,
  defs: ReturnType<typeof defineTable>[]
) {
  const out: Record<string, unknown[]> = {};
  for (const dialect of ["sqlite"] as const) {
    const built = await buildExtensionSchema({
      dialect,
      coreTableNames: CORE_TABLE_NAMES,
      entities: [],
      pluginPrefixes: new Map([[pluginName, prefix]]),
      plugins: [{ owner: { kind: "plugin", id: pluginName }, tables: defs }],
    });
    out[dialect] = built.specs;
  }
  return out as Parameters<typeof buildPluginMigration>[0]["tablesByDialect"];
}

describe("plugin migrations against a real database (sqlite)", () => {
  let sqlite: Database.Database;
  let db: unknown;

  const notesA = defineTable(
    "notes",
    {
      id: col.id(),
      label: col.shortText(),
      ...col.timestamps(),
    },
    { indexes: [{ columns: ["label"], unique: true }] }
  );
  const tagsB = defineTable("tags", {
    id: col.id(),
    name: col.shortText(),
  });

  beforeAll(async () => {
    sqlite = new Database(":memory:");
    db = drizzle({ client: sqlite });
    // The same machinery migrateCore's Phase 1 uses: it creates the ledger,
    // the owner registry and the rest of the core schema, so the phase below
    // runs against exactly the tables production gives it.
    await reconcileCore({
      db,
      dialect: DIALECT,
      logger: {
        info: () => {},
        warn: () => {},
      },
    });
  });

  afterAll(() => sqlite.close());

  async function generate(
    pluginName: string,
    version: number,
    tables: ReturnType<typeof defineTable>[],
    existing: PluginMigration[] = []
  ): Promise<PluginMigration> {
    const built = buildPluginMigration({
      pluginName,
      schemaVersion: version,
      name: `v${version}`,
      now: new Date(Date.UTC(2026, 8, 23, 10, 0, 0, version)),
      tablesByDialect: await tablesByDialect(pluginName, pluginName, tables),
      existing,
    });
    expect(built).not.toBeNull();
    return built!.module;
  }

  function phaseArgs(
    sets: Array<{ pluginName: string; migrations: PluginMigration[] }>
  ) {
    return {
      dialect: DIALECT,
      db,
      adapter: adapterFor(sqlite),
      logger: createLogger({ quiet: true }),
      pluginMigrationSets: sets.map(s => ({
        ...s,
        pluginVersion: "1.0.0",
      })),
    };
  }

  it("applies two plugins in order and records ledger and owner rows", async () => {
    const a = await generate("pluga", 1, [notesA]);
    const b = await generate("plugb", 1, [tagsB]);
    await runPluginPhase(
      phaseArgs([
        { pluginName: "pluga", migrations: [a] },
        { pluginName: "plugb", migrations: [b] },
      ]) as never
    );

    const tables = await adapterFor(sqlite).listTables();
    expect(tables).toContain("pluga__notes");
    expect(tables).toContain("plugb__tags");

    const ledger = sqlite
      .prepare(
        "SELECT filename, status FROM nextly_schema_events WHERE event_type = 'file_apply'"
      )
      .all() as Array<{ filename: string; status: string }>;
    expect(ledger.map(r => [r.filename, r.status])).toEqual([
      [`plugin:pluga/${a.name}`, "applied"],
      [`plugin:plugb/${b.name}`, "applied"],
    ]);

    const owners = sqlite
      .prepare(
        "SELECT table_name, owner_id, migrated_by FROM nextly_schema_owners"
      )
      .all() as Array<Record<string, string>>;
    expect(owners).toContainEqual({
      table_name: "pluga__notes",
      owner_id: "pluga",
      migrated_by: "plugin:pluga",
    });
  });

  it("a re-run is a no-op: no new ledger rows, no errors", async () => {
    const a = await generate("pluga", 1, [notesA]);
    const before = (
      sqlite
        .prepare("SELECT COUNT(*) AS n FROM nextly_schema_events")
        .all() as Array<{ n: number }>
    )[0].n;
    await runPluginPhase(
      phaseArgs([{ pluginName: "pluga", migrations: [a] }]) as never
    );
    const after = (
      sqlite
        .prepare("SELECT COUNT(*) AS n FROM nextly_schema_events")
        .all() as Array<{ n: number }>
    )[0].n;
    expect(after).toBe(before);
  });

  it("refuses a module edited after generation", async () => {
    const a = await generate("plugc", 1, [notesA]);
    a.dialects.sqlite.up = ["-- tampered"];
    await expect(
      runPluginPhase(
        phaseArgs([{ pluginName: "plugc", migrations: [a] }]) as never
      )
    ).rejects.toThrow(/changed since it was generated/i);
  });

  it("adopts tables that already match the module's target", async () => {
    // dev push created them: execute the module's own UP by hand first
    const c = await generate("plugd", 1, [notesA]);
    for (const stmt of c.dialects.sqlite.up) sqlite.exec(stmt);
    const before = (
      sqlite
        .prepare(
          `SELECT COUNT(*) AS n FROM nextly_schema_events WHERE filename = 'plugin:plugd/${c.name}'`
        )
        .all() as Array<{ n: number }>
    )[0].n;
    await runPluginPhase(
      phaseArgs([{ pluginName: "plugd", migrations: [c] }]) as never
    );
    const rows = sqlite
      .prepare(
        `SELECT status, statements_executed FROM nextly_schema_events WHERE filename = 'plugin:plugd/${c.name}'`
      )
      .all() as Array<{ status: string; statements_executed: number }>;
    expect(before).toBe(0);
    expect(rows[0].status).toBe("applied");
    expect(rows[0].statements_executed).toBe(0);
  });

  it("refuses adoption when the live tables were altered by hand", async () => {
    const e = await generate("pluge", 1, [notesA]);
    for (const stmt of e.dialects.sqlite.up) sqlite.exec(stmt);
    sqlite.exec("ALTER TABLE pluge__notes ADD COLUMN extra TEXT");
    await expect(
      runPluginPhase(
        phaseArgs([{ pluginName: "pluge", migrations: [e] }]) as never
      )
    ).rejects.toThrow(/cannot be applied/i);
  });
});

describe("foreign elements never block a plugin's reconcile (C7)", () => {
  let sqlite: Database.Database;
  let db: unknown;

  beforeAll(async () => {
    sqlite = new Database(":memory:");
    db = drizzle({ client: sqlite });
    await reconcileCore({
      db,
      dialect: DIALECT,
      logger: { info: () => {}, warn: () => {} },
    });
  });
  afterAll(() => sqlite.close());

  it("adopts a table carrying an app-contributed index the plugin never declared", async () => {
    // Dev push created the plugin's table WITH its own unique index and an
    // app-contributed one; the element row says whose the app's is. The
    // plugin's reconcile excludes the foreign element and adopts.
    const notes = defineTable(
      "notes",
      { id: col.id(), label: col.shortText(), ...col.timestamps() },
      { indexes: [{ columns: ["label"], unique: true }] }
    );
    const built = buildPluginMigration({
      pluginName: "plugf",
      schemaVersion: 1,
      name: "v1",
      now: new Date(Date.UTC(2026, 8, 23, 11, 0, 0)),
      tablesByDialect: await tablesByDialect("plugf", "plugf", [notes]),
      existing: [],
    });
    const g = built!.module;
    for (const stmt of g.dialects.sqlite.up) sqlite.exec(stmt);
    // The app's index on the plugin's table, plus its element owner row.
    sqlite.exec("CREATE INDEX idx_app_label ON plugf__notes (label)");
    sqlite.exec(
      `INSERT INTO nextly_schema_owners
         (table_name, element_kind, element_name, owner_kind, owner_id, migrated_by, state, created_at, updated_at)
       VALUES ('plugf__notes', 'index', 'idx_app_label', 'app', 'app', 'app', 'active', 0, 0)`
    );
    await runPluginPhase({
      dialect: DIALECT,
      db,
      adapter: adapterFor(sqlite),
      logger: createLogger({ quiet: true }),
      pluginMigrationSets: [
        { pluginName: "plugf", pluginVersion: "1.0.0", migrations: [g] },
      ],
    } as never);
    const rows = sqlite
      .prepare(
        `SELECT status, statements_executed FROM nextly_schema_events WHERE filename = 'plugin:plugf/${g.name}'`
      )
      .all() as Array<{ status: string; statements_executed: number }>;
    expect(rows[0]?.status).toBe("applied");
    expect(rows[0]?.statements_executed).toBe(0);
  });
});

describe("a plugin's first migration creates its constraints inline (C8)", () => {
  let sqlite: Database.Database;
  let db: unknown;

  beforeAll(async () => {
    sqlite = new Database(":memory:");
    db = drizzle({ client: sqlite });
    await reconcileCore({
      db,
      dialect: DIALECT,
      logger: { info: () => {}, warn: () => {} },
    });
  });
  afterAll(() => sqlite.close());

  it("applies a module whose table declares a check, and the check enforces", async () => {
    const owners = defineTable("c8owners", { id: col.id() });
    const linked = defineTable(
      "c8linked",
      { id: col.id(), ownerId: col.shortText(), score: col.integer({ nullable: true }) },
      {
        foreignKeys: [
          {
            columns: ["ownerId"],
            references: { table: "c8g__c8owners", columns: ["id"] },
            onDelete: "cascade",
          },
        ],
        checks: [{ name: "score_ok", sql: "score >= 0" }],
      }
    );
    const built = buildPluginMigration({
      pluginName: "c8g",
      schemaVersion: 1,
      name: "v1",
      now: new Date(Date.UTC(2026, 8, 24, 1, 0, 0)),
      tablesByDialect: await tablesByDialect("c8g", "c8g", [owners, linked]),
      existing: [],
    });
    const g = built!.module;
    await runPluginPhase({
      dialect: DIALECT,
      db,
      adapter: adapterFor(sqlite),
      logger: createLogger({ quiet: true }),
      pluginMigrationSets: [
        { pluginName: "c8g", pluginVersion: "1.0.0", migrations: [g] },
      ],
    } as never);
    // Both tables exist; the check enforces; the cascade fires.
    expect(await adapterFor(sqlite).listTables()).toContain("c8g__c8linked");
    let checkEnforced = false;
    try {
      sqlite.exec(
        `INSERT INTO c8g__c8linked (id, owner_id, score) VALUES ('x1', 'o1', -5)`
      );
    } catch {
      checkEnforced = true;
    }
    expect(checkEnforced).toBe(true);
    sqlite.exec(
      `INSERT INTO c8g__c8owners (id) VALUES ('o1')`
    );
    sqlite.exec(
      `INSERT INTO c8g__c8linked (id, owner_id, score) VALUES ('l1', 'o1', 3)`
    );
    sqlite.exec(`DELETE FROM c8g__c8owners WHERE id = 'o1'`);
    const remaining = sqlite
      .prepare(`SELECT COUNT(*) AS n FROM c8g__c8linked`)
      .all() as Array<{ n: number }>;
    expect(remaining[0]?.n).toBe(0);
  });
});
