/**
 * Running a unit marked to run outside a transaction again after it failed
 * part-way, on every configured dialect.
 *
 * Its schema statements ran and stayed, so the database stands at the unit's
 * target, while the data statement after the failure never ran. The
 * reconcile reads "live equals target" as a unit somebody already applied,
 * and recorded it applied with nothing run: the data change was skipped for
 * good, silently. The retry is refused instead, naming the recovery, and the
 * recovery it names is then followed through to an applied unit.
 *
 * The plugin module is generated by the real generator from the DSL; the app
 * file's target snapshot is the live table the failed attempt left, read back
 * as `migrate:create` would have recorded it.
 */
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { buildExtensionSchema } from "../../../domains/schema/extension/build-extension-schema";
import { col, defineTable } from "../../../domains/schema/extension/dsl";
import { getSchemaEventsDdl } from "../../../domains/schema/events/schema-events-ddl";
import { SchemaEventsRepository } from "../../../domains/schema/events/schema-events-repository";
import { buildPluginMigration } from "../../../domains/schema/migrate-create/generate-plugin";
import { writeSnapshot } from "../../../domains/schema/migrate-create/snapshot-io";
import {
  migrationChecksum,
  type PluginMigration,
} from "../../../domains/schema/migrate/plugin/plugin-migration";
import { resolveMigration } from "../../../domains/schema/migrate/resolve";
import { introspectLiveSnapshot } from "../../../domains/schema/pipeline/diff/introspect-live";
import {
  createTestNextly,
  getConfiguredTestDialects,
  type TestNextly,
} from "../../../plugins/test-nextly";
import { CORE_TABLE_NAMES } from "../../../schemas/index";
import { createLogger } from "../../utils/logger";
import { runFileMigrations, runPluginPhase } from "../migrate";

const ALL = ["postgresql", "mysql", "sqlite"] as const;

/** The data statement the failed attempt never reached. */
const BACKFILL = "INSERT INTO ntr_backfill (id) VALUES ('backfilled')";

/** A module creating the plugin's table, then backfilling another table. */
async function moduleWithBackfill(): Promise<PluginMigration> {
  const notes = defineTable("notes", { id: col.id(), label: col.shortText() });
  const tablesByDialect = {} as Parameters<
    typeof buildPluginMigration
  >[0]["tablesByDialect"];
  for (const dialect of ALL) {
    const built = await buildExtensionSchema({
      dialect,
      coreTableNames: CORE_TABLE_NAMES,
      entities: [],
      pluginPrefixes: new Map([["ntr", "ntr"]]),
      plugins: [{ owner: { kind: "plugin", id: "ntr" }, tables: [notes] }],
    });
    tablesByDialect[dialect] = built.specs;
  }
  const built = buildPluginMigration({
    pluginName: "ntr",
    schemaVersion: 1,
    name: "notes",
    now: new Date(Date.UTC(2026, 9, 1, 10, 0, 0)),
    tablesByDialect,
    existing: [],
  });
  if (!built) throw new Error("no module generated");
  const { checksum: _generated, ...generated } = built.module;
  const content = {
    ...generated,
    transaction: false,
    dialects: Object.fromEntries(
      ALL.map(dialect => [
        dialect,
        {
          up: [...generated.dialects[dialect].up, BACKFILL],
          down: generated.dialects[dialect].down,
        },
      ])
    ) as PluginMigration["dialects"],
  };
  return { ...content, checksum: migrationChecksum(content) };
}

describe.each(getConfiguredTestDialects())(
  "retrying a no-transaction unit that failed part-way (%s)",
  dialect => {
    let handle: TestNextly;
    let migrationsDir: string;

    beforeEach(async () => {
      handle = await createTestNextly(dialect === "sqlite" ? {} : { dialect });
      if (!(await handle.adapter.tableExists("nextly_schema_events"))) {
        for (const statement of getSchemaEventsDdl(dialect)) {
          await handle.adapter.executeQuery(statement);
        }
      }
      migrationsDir = mkdtempSync(join(tmpdir(), "nextly-ntx-retry-"));
    });

    afterEach(async () => {
      for (const table of ["ntr_backfill", "ntr_t", "ntr__notes"]) {
        await handle?.adapter.executeQuery(`DROP TABLE IF EXISTS ${table}`);
      }
      await handle?.destroy();
      if (migrationsDir)
        rmSync(migrationsDir, { recursive: true, force: true });
    });

    const repo = () =>
      new SchemaEventsRepository(handle.adapter.getDrizzle(), dialect);

    async function ledgerStatus(filename: string): Promise<string[]> {
      const rows = await repo().findFileApplies(filename);
      return [...rows]
        .sort((a, b) => +new Date(a.startedAt) - +new Date(b.startedAt))
        .map(row => row.status);
    }

    async function backfilled(): Promise<string[]> {
      const rows = (await handle.adapter.executeQuery(
        "SELECT id FROM ntr_backfill"
      )) as Array<{ id: string }>;
      return rows.map(row => row.id);
    }

    function migratePlugin(migrations: PluginMigration[]) {
      return runPluginPhase({
        extensionSchema: undefined,
        dialect,
        db: handle.adapter.getDrizzle(),
        adapter: handle.adapter as unknown as Parameters<
          typeof runPluginPhase
        >[0]["adapter"],
        migrationsDir: "unused",
        logger: createLogger({ quiet: true }),
        pluginMigrationSets: [
          { pluginName: "ntr", pluginVersion: "1.0.0", migrations },
        ],
      });
    }

    function migrate() {
      return runFileMigrations({
        adapter: handle.adapter as unknown as Parameters<
          typeof runFileMigrations
        >[0]["adapter"],
        db: handle.adapter.getDrizzle(),
        dialect,
        migrationsDir,
        logger: createLogger({ quiet: true }),
      });
    }

    it("refuses to adopt a module whose last attempt failed part-way, and adopts it once the attempt is cleared", async () => {
      const module = await moduleWithBackfill();
      const key = `plugin:ntr/${module.name}`;

      await expect(migratePlugin([module])).rejects.toThrow(
        /ran outside a transaction, and its statement \d+ of \d+ failed/
      );
      // The cause is fixed; the database now stands at the module's target.
      await handle.adapter.executeQuery(
        "CREATE TABLE ntr_backfill (id varchar(36) PRIMARY KEY)"
      );

      await expect(migratePlugin([module])).rejects.toMatchObject({
        code: "NEXTLY_MIGRATION_PARTIALLY_APPLIED",
        logContext: { reason: "partially-applied" },
        message: expect.stringContaining(
          `${key} runs outside a transaction, and its last attempt failed part-way.`
        ) as unknown,
      });
      await expect(migratePlugin([module])).rejects.toThrow(
        `run \`nextly migrate:resolve --failed-cleanup ${key}\` and then \`nextly migrate\`, which records it applied`
      );
      // Not adopted: the ledger holds the failed attempt alone, and the
      // backfill was not skipped silently.
      expect(await ledgerStatus(key)).toEqual(["failed"]);
      expect(await backfilled()).toEqual([]);

      // The recovery the refusal names: finish by hand, clear the attempt.
      await handle.adapter.executeQuery(BACKFILL);
      await resolveMigration({
        mode: "failed-cleanup",
        filename: key,
        repo: repo(),
        fileExists: () => Promise.resolve(true),
        loadTargetSnapshot: () => Promise.resolve(null),
        introspectLive: () => Promise.resolve({ tables: [] }),
      });
      await expect(migratePlugin([module])).resolves.toMatchObject({
        adopted: 1,
      });
      expect(await ledgerStatus(key)).toEqual(["rolled_back", "applied"]);
      expect(await backfilled()).toEqual(["backfilled"]);
    });

    it("refuses to adopt an app file whose last attempt failed part-way, and records it once marked applied", async () => {
      const name = "20261001_000001_retry";
      const filename = `${name}.sql`;
      const sql = `-- nextly:no-transaction\n-- Migration: retry\n\n-- UP\nCREATE TABLE ntr_t (id varchar(36) PRIMARY KEY);\n${BACKFILL};\n\n-- DOWN\n`;
      writeFileSync(join(migrationsDir, filename), sql, "utf8");

      await expect(migrate()).rejects.toThrow(
        /ran outside a transaction, and its statement 2 of 2 failed/
      );
      // The file's target, as `migrate:create` would have recorded it: the
      // table its schema statement created.
      const target = await introspectLiveSnapshot(
        handle.adapter.getDrizzle(),
        dialect,
        ["ntr_t"]
      );
      await writeSnapshot(join(migrationsDir, "meta"), name, target, sql);
      await handle.adapter.executeQuery(
        "CREATE TABLE ntr_backfill (id varchar(36) PRIMARY KEY)"
      );

      await expect(migrate()).rejects.toMatchObject({
        code: "NEXTLY_MIGRATION_PARTIALLY_APPLIED",
        message: expect.stringContaining(
          `If you finish its remaining statements by hand, mark it applied with \`nextly migrate:resolve --applied ${filename}\` rather than running it again; if you reverse the statements that ran, run \`nextly migrate\` again.`
        ) as unknown,
      });
      expect(await ledgerStatus(filename)).toEqual(["failed"]);
      expect(await backfilled()).toEqual([]);

      // The recovery the refusal names: finish by hand, mark it applied.
      await handle.adapter.executeQuery(BACKFILL);
      await expect(
        resolveMigration({
          mode: "applied",
          filename,
          repo: repo(),
          fileExists: () => Promise.resolve(true),
          loadTargetSnapshot: () => Promise.resolve(target),
          introspectLive: () =>
            introspectLiveSnapshot(handle.adapter.getDrizzle(), dialect, [
              "ntr_t",
            ]),
        })
      ).resolves.toMatchObject({ kind: "applied" });
      await expect(migrate()).resolves.toBe(0);
      expect(await backfilled()).toEqual(["backfilled"]);
    });
  }
);
