/**
 * Running a unit marked to run outside a transaction again after it failed
 * part-way, on every configured dialect.
 *
 * Its schema statements ran and stayed, so the database stands at the unit's
 * target, while the data statement after the failure never ran. The
 * reconcile reads "live equals target" as a unit somebody already applied,
 * and recorded it applied with nothing run: the data change was skipped for
 * good, silently. The retry is refused instead, naming the recovery, and the
 * recovery it names is then followed through to an applied unit.
 *
 * A unit run IN a transaction is the same case on MySQL, which commits each
 * schema statement as it runs: its failed attempt leaves the schema
 * statements before the failure applied too. On PostgreSQL and SQLite that
 * attempt was undone whole, so the retry simply runs it.
 *
 * The plugin module is generated by the real generator from the DSL; the app
 * file's target snapshot is the live table the failed attempt left, read back
 * as `migrate:create` would have recorded it.
 */
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { buildExtensionSchema } from "../../../domains/schema/extension/build-extension-schema";
import { col, defineTable } from "../../../domains/schema/extension/dsl";
import { getSchemaEventsDdl } from "../../../domains/schema/events/schema-events-ddl";
import { SchemaEventsRepository } from "../../../domains/schema/events/schema-events-repository";
import { buildPluginMigration } from "../../../domains/schema/migrate-create/generate-plugin";
import { writeSnapshot } from "../../../domains/schema/migrate-create/snapshot-io";
import {
  migrationChecksum,
  type PluginMigration,
} from "../../../domains/schema/migrate/plugin/plugin-migration";
import { resolveMigration } from "../../../domains/schema/migrate/resolve";
import { marksNoTransaction } from "../../../domains/schema/migrate/split-sql";
import { introspectLiveSnapshot } from "../../../domains/schema/pipeline/diff/introspect-live";
import {
  createTestNextly,
  getConfiguredTestDialects,
  type TestNextly,
} from "../../../plugins/test-nextly";
import { CORE_TABLE_NAMES } from "../../../schemas/index";
import { createLogger } from "../../utils/logger";
import { runFileMigrations, runPluginPhase } from "../migrate";

const ALL = ["postgresql", "mysql", "sqlite"] as const;

/** The data statement the failed attempt never reached. */
const BACKFILL = "INSERT INTO ntr_backfill (id) VALUES ('backfilled')";

/**
 * A module creating the plugin's table, then backfilling another table:
 * outside a transaction unless `inTransaction`, when it is left unmarked and
 * runs in one.
 */
async function moduleWithBackfill(
  inTransaction = false
): Promise<PluginMigration> {
  const notes = defineTable("notes", { id: col.id(), label: col.shortText() });
  const tablesByDialect = {} as Parameters<
    typeof buildPluginMigration
  >[0]["tablesByDialect"];
  for (const dialect of ALL) {
    const built = await buildExtensionSchema({
      dialect,
      coreTableNames: CORE_TABLE_NAMES,
      entities: [],
      pluginPrefixes: new Map([["ntr", "ntr"]]),
      plugins: [{ owner: { kind: "plugin", id: "ntr" }, tables: [notes] }],
    });
    tablesByDialect[dialect] = built.specs;
  }
  const built = buildPluginMigration({
    pluginName: "ntr",
    schemaVersion: 1,
    name: "notes",
    now: new Date(Date.UTC(2026, 9, 1, 10, 0, 0)),
    tablesByDialect,
    existing: [],
  });
  if (!built) throw new Error("no module generated");
  const { checksum: _generated, ...generated } = built.module;
  const content = {
    ...generated,
    ...(inTransaction ? {} : { transaction: false }),
    dialects: Object.fromEntries(
      ALL.map(dialect => [
        dialect,
        {
          up: [...generated.dialects[dialect].up, BACKFILL],
          down: generated.dialects[dialect].down,
        },
      ])
    ) as PluginMigration["dialects"],
  };
  return { ...content, checksum: migrationChecksum(content) };
}

describe.each(getConfiguredTestDialects())(
  "retrying a no-transaction unit that failed part-way (%s)",
  dialect => {
    let handle: TestNextly;
    let migrationsDir: string;

    beforeEach(async () => {
      handle = await createTestNextly(dialect === "sqlite" ? {} : { dialect });
      if (!(await handle.adapter.tableExists("nextly_schema_events"))) {
        for (const statement of getSchemaEventsDdl(dialect)) {
          await handle.adapter.executeQuery(statement);
        }
      }
      migrationsDir = mkdtempSync(join(tmpdir(), "nextly-ntx-retry-"));
    });

    afterEach(async () => {
      for (const table of ["ntr_backfill", "ntr_t", "ntr__notes"]) {
        await handle?.adapter.executeQuery(`DROP TABLE IF EXISTS ${table}`);
      }
      await handle?.destroy();
      if (migrationsDir)
        rmSync(migrationsDir, { recursive: true, force: true });
    });

    const repo = () =>
      new SchemaEventsRepository(handle.adapter.getDrizzle(), dialect);

    async function ledgerStatus(filename: string): Promise<string[]> {
      const rows = await repo().findFileApplies(filename);
      return [...rows]
        .sort((a, b) => +new Date(a.startedAt) - +new Date(b.startedAt))
        .map(row => row.status);
    }

    async function backfilled(): Promise<string[]> {
      const rows = (await handle.adapter.executeQuery(
        "SELECT id FROM ntr_backfill"
      )) as Array<{ id: string }>;
      return rows.map(row => row.id);
    }

    function migratePlugin(migrations: PluginMigration[]) {
      return runPluginPhase({
        extensionSchema: undefined,
        dialect,
        db: handle.adapter.getDrizzle(),
        adapter: handle.adapter as unknown as Parameters<
          typeof runPluginPhase
        >[0]["adapter"],
        migrationsDir: "unused",
        logger: createLogger({ quiet: true }),
        pluginMigrationSets: [
          { pluginName: "ntr", pluginVersion: "1.0.0", migrations },
        ],
      });
    }

    function migrate() {
      return runFileMigrations({
        adapter: handle.adapter as unknown as Parameters<
          typeof runFileMigrations
        >[0]["adapter"],
        db: handle.adapter.getDrizzle(),
        dialect,
        migrationsDir,
        logger: createLogger({ quiet: true }),
      });
    }

    it("refuses to adopt a module whose last attempt failed part-way, and adopts it once the attempt is cleared", async () => {
      const module = await moduleWithBackfill();
      const key = `plugin:ntr/${module.name}`;

      await expect(migratePlugin([module])).rejects.toThrow(
        /ran outside a transaction, and its statement \d+ of \d+ failed/
      );
      // The cause is fixed; the database now stands at the module's target.
      await handle.adapter.executeQuery(
        "CREATE TABLE ntr_backfill (id varchar(36) PRIMARY KEY)"
      );

      await expect(migratePlugin([module])).rejects.toMatchObject({
        code: "NEXTLY_MIGRATION_PARTIALLY_APPLIED",
        logContext: { reason: "partially-applied" },
        message: expect.stringContaining(
          `${key} runs outside a transaction, and its last attempt failed part-way.`
        ) as unknown,
      });
      await expect(migratePlugin([module])).rejects.toThrow(
        `run \`nextly migrate:resolve --failed-cleanup ${key}\` and then \`nextly migrate\`, which records it applied`
      );
      // Not adopted: the ledger holds the failed attempt alone, and the
      // backfill was not skipped silently.
      expect(await ledgerStatus(key)).toEqual(["failed"]);
      expect(await backfilled()).toEqual([]);

      // The recovery the refusal names: finish by hand, clear the attempt.
      await handle.adapter.executeQuery(BACKFILL);
      await resolveMigration({
        mode: "failed-cleanup",
        filename: key,
        dialect,
        repo: repo(),
        fileExists: () => Promise.resolve(true),
        loadTargetSnapshot: () => Promise.resolve(null),
        marksNoTransaction: () => Promise.resolve(false),
        introspectLive: () => Promise.resolve({ tables: [] }),
      });
      await expect(migratePlugin([module])).resolves.toMatchObject({
        adopted: 1,
      });
      expect(await ledgerStatus(key)).toEqual(["rolled_back", "applied"]);
      expect(await backfilled()).toEqual(["backfilled"]);
    });

    it("refuses to adopt an app file whose last attempt failed part-way, and records it once marked applied", async () => {
      const name = "20261001_000001_retry";
      const filename = `${name}.sql`;
      const sql = `-- nextly:no-transaction\n-- Migration: retry\n\n-- UP\nCREATE TABLE ntr_t (id varchar(36) PRIMARY KEY);\n${BACKFILL};\n\n-- DOWN\n`;
      writeFileSync(join(migrationsDir, filename), sql, "utf8");

      await expect(migrate()).rejects.toThrow(
        /ran outside a transaction, and its statement 2 of 2 failed/
      );
      // The file's target, as `migrate:create` would have recorded it: the
      // table its schema statement created.
      const target = await introspectLiveSnapshot(
        handle.adapter.getDrizzle(),
        dialect,
        ["ntr_t"]
      );
      await writeSnapshot(join(migrationsDir, "meta"), name, target, sql);
      await handle.adapter.executeQuery(
        "CREATE TABLE ntr_backfill (id varchar(36) PRIMARY KEY)"
      );

      await expect(migrate()).rejects.toMatchObject({
        code: "NEXTLY_MIGRATION_PARTIALLY_APPLIED",
        message: expect.stringContaining(
          `If you finish its remaining statements by hand, mark it applied with \`nextly migrate:resolve --applied ${filename}\` rather than running it again; if you reverse the statements that ran, run \`nextly migrate:resolve --failed-cleanup ${filename}\` and then \`nextly migrate\` again.`
        ) as unknown,
      });
      expect(await ledgerStatus(filename)).toEqual(["failed"]);
      expect(await backfilled()).toEqual([]);

      // The recovery the refusal names: finish by hand, mark it applied.
      await handle.adapter.executeQuery(BACKFILL);
      await expect(
        resolveMigration({
          mode: "applied",
          filename,
          dialect,
          repo: repo(),
          fileExists: () => Promise.resolve(true),
          loadTargetSnapshot: () => Promise.resolve(target),
          marksNoTransaction: () => Promise.resolve(true),
          introspectLive: () =>
            introspectLiveSnapshot(handle.adapter.getDrizzle(), dialect, [
              "ntr_t",
            ]),
        })
      ).resolves.toMatchObject({ kind: "applied" });
      await expect(migrate()).resolves.toBe(0);
      expect(await backfilled()).toEqual(["backfilled"]);
    });

    it("never skips the data statement of a module run in a transaction whose last attempt failed", async () => {
      const module = await moduleWithBackfill(true);
      const key = `plugin:ntr/${module.name}`;

      await expect(migratePlugin([module])).rejects.toMatchObject({
        code: "NEXTLY_MIGRATION_APPLY_FAILED",
      });
      await handle.adapter.executeQuery(
        "CREATE TABLE ntr_backfill (id varchar(36) PRIMARY KEY)"
      );

      if (dialect === "mysql") {
        // The CREATE TABLE committed before the INSERT failed, so the
        // database stands at the module's target with the backfill unrun.
        await expect(migratePlugin([module])).rejects.toMatchObject({
          code: "NEXTLY_MIGRATION_PARTIALLY_APPLIED",
          message: expect.stringContaining(
            `${key}'s last attempt failed, and MySQL commits each schema statement as it runs`
          ) as unknown,
        });
        expect(await ledgerStatus(key)).toEqual(["failed"]);
        expect(await backfilled()).toEqual([]);
        return;
      }
      // The failed attempt was undone whole: the retry runs the module.
      await expect(migratePlugin([module])).resolves.toMatchObject({
        applied: 1,
      });
      expect(await ledgerStatus(key)).toEqual(["failed", "applied"]);
      expect(await backfilled()).toEqual(["backfilled"]);
    });

    it("never skips the data statement of an app file run in a transaction whose last attempt failed", async () => {
      const name = "20261001_000002_retry";
      const filename = `${name}.sql`;
      const sql = `-- Migration: retry\n\n-- UP\nCREATE TABLE ntr_t (id varchar(36) PRIMARY KEY);\n${BACKFILL};\n\n-- DOWN\n`;
      writeFileSync(join(migrationsDir, filename), sql, "utf8");

      await expect(migrate()).rejects.toThrow(/ntr_backfill/);
      // The file's target, as `migrate:create` recorded it: the table its
      // schema statement creates, read from where MySQL left it.
      if (dialect === "mysql") {
        const target = await introspectLiveSnapshot(
          handle.adapter.getDrizzle(),
          dialect,
          ["ntr_t"]
        );
        await writeSnapshot(join(migrationsDir, "meta"), name, target, sql);
      }
      await handle.adapter.executeQuery(
        "CREATE TABLE ntr_backfill (id varchar(36) PRIMARY KEY)"
      );

      if (dialect === "mysql") {
        await expect(migrate()).rejects.toMatchObject({
          code: "NEXTLY_MIGRATION_PARTIALLY_APPLIED",
          message: expect.stringContaining(
            `mark it applied with \`nextly migrate:resolve --applied ${filename}\``
          ) as unknown,
        });
        expect(await ledgerStatus(filename)).toEqual(["failed"]);
        expect(await backfilled()).toEqual([]);
        return;
      }
      await expect(migrate()).resolves.toBe(1);
      expect(await backfilled()).toEqual(["backfilled"]);
    });

    /**
     * Two app files with snapshots: the first creates `ntr_t`, the second
     * backfills and then adds a unique index on `ntr_t.label`, which fails
     * while two rows share a label. Its schema statement failed, so the
     * database stands where the second file starts whatever became of the
     * backfill before it.
     */
    async function backfillThenIndex(
      marked: boolean,
      withSnapshot: boolean
    ): Promise<string> {
      const first = "20261001_000003_table";
      const firstSql = `-- Migration: table\n\n-- UP\nCREATE TABLE ntr_t (id varchar(36) PRIMARY KEY, label varchar(36));\n\n-- DOWN\n`;
      writeFileSync(join(migrationsDir, `${first}.sql`), firstSql, "utf8");
      await expect(migrate()).resolves.toBe(1);
      const meta = join(migrationsDir, "meta");
      const live = () =>
        introspectLiveSnapshot(handle.adapter.getDrizzle(), dialect, ["ntr_t"]);
      await writeSnapshot(meta, first, await live(), firstSql);

      // The second file's target, as `migrate:create` would have recorded
      // it: the table with the index, read back and then undone.
      const index = "CREATE UNIQUE INDEX ntr_t_label_uq ON ntr_t (label)";
      await handle.adapter.executeQuery(index);
      const target = await live();
      await handle.adapter.executeQuery(
        dialect === "mysql"
          ? "DROP INDEX ntr_t_label_uq ON ntr_t"
          : "DROP INDEX ntr_t_label_uq"
      );
      const second = "20261001_000004_backfill";
      const secondSql = `${marked ? "-- nextly:no-transaction\n" : ""}-- Migration: backfill\n\n-- UP\n${BACKFILL};\n${index};\n\n-- DOWN\n`;
      writeFileSync(join(migrationsDir, `${second}.sql`), secondSql, "utf8");
      if (withSnapshot) await writeSnapshot(meta, second, target, secondSql);

      // No key on the backfill table, so a second run of the file inserts
      // a second row rather than failing on the first.
      await handle.adapter.executeQuery(
        "CREATE TABLE ntr_backfill (id varchar(36))"
      );
      await handle.adapter.executeQuery(
        "INSERT INTO ntr_t (id, label) VALUES ('a', 'same'), ('b', 'same')"
      );
      await expect(migrate()).rejects.toThrow();
      // The cause is fixed; the index can now be built.
      await handle.adapter.executeQuery("DELETE FROM ntr_t WHERE id = 'b'");
      return `${second}.sql`;
    }

    // With a snapshot the reconcile places the database at the file's start;
    // without one the file is run verbatim, and the same refusal holds.
    for (const withSnapshot of [true, false]) {
      const shape = withSnapshot ? "with a snapshot" : "without a snapshot";
      it(`never runs again a file in a transaction whose failed attempt may have left its backfill (${shape})`, async () => {
        const filename = await backfillThenIndex(false, withSnapshot);

        if (dialect === "mysql") {
          // MySQL committed the backfill when the index statement began, so
          // running the file again would insert it a second time.
          expect(await backfilled()).toEqual(["backfilled"]);
          await expect(migrate()).rejects.toMatchObject({
            code: "NEXTLY_MIGRATION_PARTIALLY_APPLIED",
            message: expect.stringContaining(
              `${filename}'s last attempt failed, and MySQL commits each schema statement as it runs`
            ) as unknown,
          });
          expect(await ledgerStatus(filename)).toEqual(["failed"]);
          expect(await backfilled()).toEqual(["backfilled"]);

          // The recovery the refusal names: reverse what ran, clear the
          // attempt, migrate. The file then runs once, and its backfill is
          // there once.
          await handle.adapter.executeQuery("DELETE FROM ntr_backfill");
          await resolveMigration({
            mode: "failed-cleanup",
            filename,
            dialect,
            repo: repo(),
            fileExists: () => Promise.resolve(true),
            loadTargetSnapshot: () => Promise.resolve(null),
            marksNoTransaction: () => Promise.resolve(false),
            introspectLive: () => Promise.resolve({ tables: [] }),
          });
          await expect(migrate()).resolves.toBe(1);
          expect(await ledgerStatus(filename)).toEqual([
            "rolled_back",
            "applied",
          ]);
          expect(await backfilled()).toEqual(["backfilled"]);
          return;
        }
        // The failed attempt was undone whole: the retry runs the file once.
        expect(await backfilled()).toEqual([]);
        await expect(migrate()).resolves.toBe(1);
        expect(await ledgerStatus(filename)).toEqual(["failed", "applied"]);
        expect(await backfilled()).toEqual(["backfilled"]);
      });

      if (!withSnapshot) {
        it("marks applied a file in a transaction with no snapshot once it is finished by hand, unverified only where its attempt may have stopped part-way", async () => {
          const filename = await backfillThenIndex(false, false);
          const path = join(migrationsDir, filename);
          const snapshotPath = join(
            migrationsDir,
            "meta",
            filename.replace(/\.sql$/, ".snapshot.json")
          );

          if (dialect === "mysql") {
            // The advice an unmarked `--blank` file on MySQL is given.
            await expect(migrate()).rejects.toMatchObject({
              code: "NEXTLY_MIGRATION_PARTIALLY_APPLIED",
              message: expect.stringContaining(
                `mark it applied with \`nextly migrate:resolve --applied ${filename}\``
              ) as unknown,
            });
          } else {
            // The failed attempt was undone whole; finishing it by hand here
            // is the operator's choice rather than the advice.
            await handle.adapter.executeQuery(BACKFILL);
          }
          // Finished by hand: the statement that failed now builds.
          await handle.adapter.executeQuery(
            "CREATE UNIQUE INDEX ntr_t_label_uq ON ntr_t (label)"
          );

          // The file's own state, read as `migrate:resolve` reads it: no
          // snapshot beside it, and no marker on its first line.
          expect(existsSync(snapshotPath)).toBe(false);
          const markApplied = (skipVerify?: boolean) =>
            resolveMigration({
              mode: "applied",
              filename,
              skipVerify,
              dialect,
              repo: repo(),
              fileExists: () => Promise.resolve(existsSync(path)),
              loadTargetSnapshot: () => Promise.resolve(null),
              marksNoTransaction: () =>
                Promise.resolve(marksNoTransaction(readFileSync(path, "utf8"))),
              introspectLive: () =>
                Promise.reject(new Error("nothing to compare it with")),
            });

          if (dialect !== "mysql") {
            // None of the failed attempt ran, so recording the file with
            // nothing compared would record a file that never ran: that
            // stays the operator's explicit `--skip-verify`.
            await expect(markApplied()).rejects.toMatchObject({
              code: "NEXTLY_MIGRATION_SNAPSHOT_MISSING",
            });
            expect(await ledgerStatus(filename)).toEqual(["failed"]);
          }
          await expect(
            markApplied(dialect === "mysql" ? undefined : true)
          ).resolves.toMatchObject({ kind: "applied", verified: false });

          // Recorded, so the next run neither refuses it nor repeats it.
          await expect(migrate()).resolves.toBe(0);
          expect(await ledgerStatus(filename)).toEqual([
            "superseded",
            "applied",
          ]);
          expect(await backfilled()).toEqual(["backfilled"]);
        });
      }

      it(`never runs again a file outside a transaction whose failed attempt left its backfill, until the attempt is reversed and cleared (${shape})`, async () => {
        const filename = await backfillThenIndex(true, withSnapshot);
        expect(await backfilled()).toEqual(["backfilled"]);

        await expect(migrate()).rejects.toMatchObject({
          code: "NEXTLY_MIGRATION_PARTIALLY_APPLIED",
          message: expect.stringContaining(
            `run \`nextly migrate:resolve --failed-cleanup ${filename}\` and then \`nextly migrate\` again`
          ) as unknown,
        });
        expect(await backfilled()).toEqual(["backfilled"]);

        // The recovery the refusal names: reverse what ran, clear the attempt.
        await handle.adapter.executeQuery("DELETE FROM ntr_backfill");
        await resolveMigration({
          mode: "failed-cleanup",
          filename,
          dialect,
          repo: repo(),
          fileExists: () => Promise.resolve(true),
          loadTargetSnapshot: () => Promise.resolve(null),
          marksNoTransaction: () => Promise.resolve(true),
          introspectLive: () => Promise.resolve({ tables: [] }),
        });
        await expect(migrate()).resolves.toBe(1);
        expect(await ledgerStatus(filename)).toEqual([
          "rolled_back",
          "applied",
        ]);
        expect(await backfilled()).toEqual(["backfilled"]);
      });
    }
  }
);
