/**
 * The plugin migration phase on a database the app or dev push already used,
 * on every configured dialect.
 *
 * A fresh database is the easy case: every module finds its start and runs.
 * Every existing install is the other one. Its collection tables are in the
 * database, which a plugin's snapshots never name, and dev push has already
 * created the plugin's tables in their CURRENT shape, the last module's
 * result, which the first module's start and end both differ from. Both of
 * those once made `nextly migrate` refuse a database nothing was wrong with.
 *
 * The modules are generated by the real generator from the DSL, for all three
 * dialects at once as `migrate:create --plugin` does, and each test reads the
 * outcome back from the ledger rather than from what the phase returned.
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { buildExtensionSchema } from "../../../domains/schema/extension/build-extension-schema";
import { col, defineTable } from "../../../domains/schema/extension/dsl";
import { getSchemaEventsDdl } from "../../../domains/schema/events/schema-events-ddl";
import { SchemaEventsRepository } from "../../../domains/schema/events/schema-events-repository";
import { SchemaOwnersRepository } from "../../../domains/schema/ownership/schema-owners-repository";
import { buildPluginMigration } from "../../../domains/schema/migrate-create/generate-plugin";
import {
  pluginModuleStatements,
  type PluginMigration,
} from "../../../domains/schema/migrate/plugin/plugin-migration";
import {
  createTestNextly,
  getConfiguredTestDialects,
  type TestNextly,
} from "../../../plugins/test-nextly";
import { CORE_TABLE_NAMES } from "../../../schemas/index";
import { createLogger } from "../../utils/logger";
import { runPluginPhase } from "../migrate";
import {
  buildMigrationStatuses,
  ledgerRecords,
  migrationEntries,
} from "../migrate-status";

const ALL = ["postgresql", "mysql", "sqlite"] as const;

/** The plugin's first shape: one table with a unique index. */
const notesV1 = defineTable(
  "notes",
  { id: col.id(), label: col.shortText(), ...col.timestamps() },
  { indexes: [{ columns: ["label"], unique: true }] }
);

/** Its second shape: one column more, as a later release ships it. */
const notesV2 = defineTable(
  "notes",
  {
    id: col.id(),
    label: col.shortText(),
    score: col.integer({ nullable: true }),
    ...col.timestamps(),
  },
  { indexes: [{ columns: ["label"], unique: true }] }
);

/** One module, generated for every dialect by the real generator. */
async function generate(
  plugin: string,
  version: number,
  table: ReturnType<typeof defineTable>,
  existing: PluginMigration[] = []
): Promise<PluginMigration> {
  const tablesByDialect = {} as Parameters<
    typeof buildPluginMigration
  >[0]["tablesByDialect"];
  for (const dialect of ALL) {
    const built = await buildExtensionSchema({
      dialect,
      coreTableNames: CORE_TABLE_NAMES,
      entities: [],
      pluginPrefixes: new Map([[plugin, plugin]]),
      plugins: [{ owner: { kind: "plugin", id: plugin }, tables: [table] }],
    });
    tablesByDialect[dialect] = built.specs;
  }
  const built = buildPluginMigration({
    pluginName: plugin,
    schemaVersion: version,
    name: `v${version}`,
    now: new Date(Date.UTC(2026, 9, 1, 10, 0, 0, version)),
    tablesByDialect,
    existing,
  });
  if (!built) throw new Error(`no module generated for ${plugin} v${version}`);
  return built.module;
}

describe.each(getConfiguredTestDialects())(
  "plugin migrations on an existing database (%s)",
  dialect => {
    let handle: TestNextly;
    let v1: PluginMigration;
    let v2: PluginMigration;

    beforeAll(async () => {
      handle = await createTestNextly(dialect === "sqlite" ? {} : { dialect });
      // The ledger, as `nextly migrate` bootstraps it before this phase.
      if (!(await handle.adapter.tableExists("nextly_schema_events"))) {
        for (const statement of getSchemaEventsDdl(dialect)) {
          await handle.adapter.executeQuery(statement);
        }
      }
      v1 = await generate("plugx", 1, notesV1);
      v2 = await generate("plugx", 2, notesV2, [v1]);
    });

    afterAll(async () => {
      await handle?.destroy();
    });

    /** Run the phase as `migrateCore` does, for one plugin's modules. */
    async function runPhase(plugin: string, migrations: PluginMigration[]) {
      await runPluginPhase({
        extensionSchema: undefined,
        dialect,
        db: handle.adapter.getDrizzle(),
        adapter: handle.adapter as unknown as Parameters<
          typeof runPluginPhase
        >[0]["adapter"],
        migrationsDir: "unused",
        logger: createLogger({ quiet: true }),
        pluginMigrationSets: [
          { pluginName: plugin, pluginVersion: "1.0.0", migrations },
        ],
      });
    }

    /** The ledger rows for one plugin: which ran and which were adopted. */
    async function ledger(plugin: string) {
      const repo = new SchemaEventsRepository(
        handle.adapter.getDrizzle(),
        dialect
      );
      const rows = (await repo.listFileApplies()).filter(row =>
        (row.filename ?? "").startsWith(`plugin:${plugin}/`)
      );
      return rows
        .map(row => ({
          filename: row.filename ?? "",
          status: row.status,
          ran: (row.statementsExecuted ?? 0) > 0,
        }))
        .sort((a, b) => a.filename.localeCompare(b.filename));
    }

    /** A module's UP, run by hand: the tables dev push would have created. */
    async function runByHand(...modules: PluginMigration[]) {
      for (const module of modules) {
        // Split as the runner splits them: one entry may hold a table and
        // its indexes, which no driver takes as one statement.
        for (const statement of pluginModuleStatements(module, dialect, "up")) {
          await handle.adapter.executeQuery(statement);
        }
      }
    }

    it("runs a plugin's modules beside tables the app already has", async () => {
      // An app table the plugin's snapshots never mention. Judging the plugin
      // against every table in the database read this as drift.
      await handle.adapter.executeQuery(
        dialect === "mysql"
          ? "CREATE TABLE dc_app_posts (id varchar(36) PRIMARY KEY)"
          : 'CREATE TABLE "dc_app_posts" ("id" text PRIMARY KEY)'
      );
      const a1 = await generate("pluga", 1, notesV1);
      const a2 = await generate("pluga", 2, notesV2, [a1]);

      await runPhase("pluga", [a1, a2]);

      expect(await ledger("pluga")).toEqual([
        { filename: `plugin:pluga/${a1.name}`, status: "applied", ran: true },
        { filename: `plugin:pluga/${a2.name}`, status: "applied", ran: true },
      ]);
    });

    it("adopts a two-module history that dev push left at its latest shape", async () => {
      // Dev push creates the plugin's tables as the plugin defines them now:
      // the second module's result, which the first module's start and end
      // both differ from.
      await runByHand(v1, v2);

      await runPhase("plugx", [v1, v2]);

      expect(await ledger("plugx")).toEqual([
        { filename: `plugin:plugx/${v1.name}`, status: "applied", ran: false },
        { filename: `plugin:plugx/${v2.name}`, status: "applied", ran: false },
      ]);
    });

    it("adopts the first module and runs the second on a database left at the first", async () => {
      const b1 = await generate("plugb", 1, notesV1);
      const b2 = await generate("plugb", 2, notesV2, [b1]);
      await runByHand(b1);

      await runPhase("plugb", [b1, b2]);

      expect(await ledger("plugb")).toEqual([
        { filename: `plugin:plugb/${b1.name}`, status: "applied", ran: false },
        { filename: `plugin:plugb/${b2.name}`, status: "applied", ran: true },
      ]);
    });

    it("records the ownership a run stopped before writing, once every module is recorded", async () => {
      const r1 = await generate("plugr", 1, notesV1);
      const r2 = await generate("plugr", 2, notesV2, [r1]);
      await runPhase("plugr", [r1, r2]);
      const owners = new SchemaOwnersRepository(
        handle.adapter.getDrizzle(),
        dialect
      );
      const mine = async () =>
        (await owners.read())
          .filter(row => row.ownerId === "plugr")
          .map(row => ({ table: row.tableName, version: row.schemaVersion }));
      const claimed = r2.snapshot[dialect].tables.map(table => ({
        table: table.name,
        version: 2,
      }));
      expect(await mine()).toEqual(claimed);

      // What a run that stopped between the module's ledger row and its
      // owner rows leaves: both modules recorded applied, no table claimed.
      await owners.deleteByOwner("plugr");
      await runPhase("plugr", [r1, r2]);

      expect(await mine()).toEqual(claimed);
      expect(await ledger("plugr")).toEqual([
        { filename: `plugin:plugr/${r1.name}`, status: "applied", ran: true },
        { filename: `plugin:plugr/${r2.name}`, status: "applied", ran: true },
      ]);
    });

    it("lists a module no run has applied yet as pending in the plugin's status", async () => {
      const s1 = await generate("plugs", 1, notesV1);
      const s2 = await generate("plugs", 2, notesV2, [s1]);
      await runPhase("plugs", [s1]);

      const entries = await migrationEntries({
        plugin: "plugs",
        plugins: [
          {
            name: "plugs",
            version: "1.0.0",
            nextly: "*",
            contributes: { schema: { migrations: [s1, s2] } },
          },
        ],
        migrationsDir: "unused",
        dialect,
      });
      const repo = new SchemaEventsRepository(
        handle.adapter.getDrizzle(),
        dialect
      );
      const statuses = buildMigrationStatuses(
        entries,
        ledgerRecords(await repo.listFileApplies(), "plugs")
      );

      expect(statuses.map(s => [s.filename, s.status])).toEqual([
        [`plugin:plugs/${s1.name}`, "applied"],
        [`plugin:plugs/${s2.name}`, "pending"],
      ]);
    });
  }
);
